### ISSUE TITLE
Adding new monster crashed site

### ISSUE THREAD

**Issue by Bundy169** [AdventureLookup/AdventureLookup#100]
Added new monster. In 'Type' I added two values separated by a semi colon. After saving immediately received 500 Internal Server Error.

**Comment by cmfcmf** [comment]
For reference, this is the error that caused the failure:
> Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO monster (name, is_unique, created_by, updated_by) VALUES (?, ?, ?, ?)' with params ["Xaxinaar", 1, "Casson", "Casson"]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Xaxinaar' for key 'UNIQ_245EC6F45E237E06'" at /var/www/new.adventurelookup.com/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 66

From looking at the data your browser sent when submitting the form, we can see that your browser indeed sent the new monster twice:
```
# Ignored
&appbundle_adventure%5Bmonsters%5D%5B%5D=nXaxinaar
# First time
&appbundle_adventure%5Bmonsters-new%5D%5B1%5D%5Bname%5D=Xaxinaar
&appbundle_adventure%5Bmonsters-new%5D%5B1%5D%5BisUnique%5D=1
# Second time
&appbundle_adventure%5Bmonsters-new%5D%5B2%5D%5Bname%5D=Xaxinaar
&appbundle_adventure%5Bmonsters-new%5D%5B2%5D%5BisUnique%5D=1
```

Please note that I'm deliberately saying "your browser" and not "you". There might be an issue with the edit form. I'll try to reproduce the problem locally.

**Comment by cmfcmf** [comment]
This shouldn't happen any longer - please report if you experience issues again.
