### ISSUE TITLE
New Environment

### ISSUE THREAD

**Issue by Bundy169** [AdventureLookup/AdventureLookup#101]
'Lair' should be added to environment

**Comment by cmfcmf** [comment]
@MattColville you should decide on this feature request - if you agree, add a new Lair environment through the admin interface. If not, we can close this issue.

**Comment by MattColville** [comment]
Oh, sorry! I think "lair" is too abstract, technically any boss monster's home could be considered its "lair."

And I think if folks want to, for instance, fight a dragon in its lair, they can search for a Dragon Villain and they'll get a good list.
