### ISSUE TITLE
Are we ready for the video?

### ISSUE THREAD

**Issue by MattColville** [AdventureLookup/AdventureLookup#114]
It seemed like we were close to being ready on Friday but then Jerry told me the site crashed and there's a bug with the index.

Are we still having that problem where the index occasionally breaks if someone monkeys with an existing record? 

Are there any other outstanding issues that need to be addressed before we announce? You guys have done a colossal amount of work and I want to make sure the site is stable before we show it off.

**Comment by cmfcmf** [comment]
> It seemed like we were close to being ready on Friday but then Jerry told me the site crashed and there's a bug with the index.

Indeed, there was quite a nasty bug which crashed the site whenever somebody edited an adventure. I quickly found a solution to fix the issue, but it took a while to deploy it to the production server - timezones and weekends are difficult. Since then the index hasn't crashed again.

> Are we still having that problem where the index occasionally breaks if someone monkeys with an existing record?

I'm pretty certain the index shouldn't break any longer. If it does, or if any part of the site breaks, Jerry and I now receive an email with the error. This allows me to quickly fix it and hand it over to Jerry to deploy it. 

> Are there any other outstanding issues that need to be addressed before we announce? 

I think most, if not all, important issues have been fixed already. Users can't randomly edit and delete adventures of other people, NPCs have been removed, many other fixes have been made. However, the NPC fix and [some other minor fixes I did over the last few days](https://github.com/AdventureLookup/AdventureLookup/compare/master...dev) have not yet been merged into master and deployed to the production server. If @harkenn doesn't see any other issues, we can merge them into master today and ask @JohnnyFlash to deploy them to the live server. This might be the last step required before you can make a video.

> You guys have done a colossal amount of work and I want to make sure the site is stable before we show it off.

Thank you! I'm super excited to see my project (from a programming point of view) come more and more to life and being used by more and more people. After I spent so many hours and days of my time working on Adventure Lookup, I'm glad that about 15 months after your original video you will be able to say *someone did it*!

**Comment by MattColville** [comment]
Ok, then what I propose we do is migrate over to www.adventurelookup.com ASAP and I'll tweet about it, and then this weekend if everything's still stable, make a video.

@JohnnyFlash

**Comment by cmfcmf** [comment]
Pull request to merge changes into master created in #116.

**Comment by harkenn** [comment]
Waiting for build, then will merge

**Comment by JohnnyFlash** [comment]
I got the following error with the new master:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'prod' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 verbose run-script [ 'preprod', 'prod', 'postprod' ]
5 info lifecycle @~preprod: @
6 silly lifecycle @~preprod: no script for preprod, continuing
7 info lifecycle @~prod: @
8 verbose lifecycle @~prod: unsafe-perm in lifecycle true
9 verbose lifecycle @~prod: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/var/www/new.adventurelookup.com/html/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle @~prod: CWD: /var/www/new.adventurelookup.com/html
11 silly lifecycle @~prod: Args: [ '-c', 'webpack -p' ]
12 silly lifecycle @~prod: Returned: code: 2  signal: null
13 info lifecycle @~prod: Failed to exec prod script
14 verbose stack Error: @ prod: `webpack -p`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid @
16 verbose cwd /var/www/new.adventurelookup.com/html
17 error Linux 4.4.0-87-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "prod"
19 error node v6.11.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error @ prod: `webpack -p`
22 error Exit status 2
23 error Failed at the @ prod script 'webpack -p'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack -p
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by cmfcmf** [comment]
> I got the following error with the new master:

Hmm, weird. It worked well when running it locally or on the dev server. Here are a few things to try:
1. Update npm: `sudo npm install -g npm && npm run prod`
2. Clear installed dependencies `rm -rf node_modules && npm run prod`
3. If nothing works, upload compiled files ([assets.zip](https://github.com/AdventureLookup/AdventureLookup/files/1216543/assets.zip)) manually by extracting them into `web/assets` like this: 
![image](https://user-images.githubusercontent.com/2145092/29194883-ff779e3e-7e2b-11e7-8e51-0a7ea791d539.png)

**Comment by JohnnyFlash** [comment]
The error has changed:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'prod' ]
2 info using npm@5.3.0
3 info using node@v6.11.2
4 verbose run-script [ 'preprod', 'prod', 'postprod' ]
5 info lifecycle @~preprod: @
6 info lifecycle @~prod: @
7 verbose lifecycle @~prod: unsafe-perm in lifecycle true
8 verbose lifecycle @~prod: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/var/www/new.adventurelookup.com/html/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle @~prod: CWD: /var/www/new.adventurelookup.com/html
10 silly lifecycle @~prod: Args: [ '-c', 'webpack -p' ]
11 silly lifecycle @~prod: Returned: code: 1  signal: null
12 info lifecycle @~prod: Failed to exec prod script
13 verbose stack Error: @ prod: `webpack -p`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:891:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid @
15 verbose cwd /var/www/new.adventurelookup.com/html
16 verbose Linux 4.4.0-87-generic
17 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "prod"
18 verbose node v6.11.2
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error @ prod: `webpack -p`
22 error Exit status 1
23 error Failed at the @ prod script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by harkenn** [comment]
There is almost certainly some dependencies listed in `devDependencies` that are actually required for production. When they get excluded because of `npm run prod` the server fails to build properly.

**Comment by cmfcmf** [comment]
Did you also try step 2, @JohnnyFlash? @harkenn I don't think so, because it works locally and on the dev server.

**Comment by JohnnyFlash** [comment]
I tried all 3 options

**Comment by cmfcmf** [comment]
Oh no. I think I found it. @harkenn was almost right. The update script is missing a call to `npm install && npm run prod` should work!

**Comment by JohnnyFlash** [comment]
Ran clean today.  I think we're good.

**Comment by cmfcmf** [comment]
For reference, here's the video: https://www.youtube.com/watch?v=D3OllWSRhuI
