### ISSUE TITLE
Don't display starting level as range when min. and max. level is the same

### ISSUE THREAD

**Issue by tobloef** [AdventureLookup/AdventureLookup#122]
I noticed that some adventures have starting levels displayed as ranges, even though the minimum and maximum starting levels are the same. For example, the starting level for [Dead in Thay](https://www.adventurelookup.com/adventures/dead-in-thay-5e) is displayed as "9-9". Wouldn't it be better to just display it as "9"?

**Comment by cmfcmf** [comment]
Hi @tobloef, thank you for your suggestion! I've incorporated it in pull request #166. We'll close this issue once it's merged and deployed to the live site.

**Comment by cmfcmf** [comment]
This is now live at https://adventurelookup.com!
