### ISSUE TITLE
Feature request: price filter

### ISSUE THREAD

**Issue by patteb** [AdventureLookup/AdventureLookup#123]
While browsing for an adventure to run, I tend to have a glance at the price of it. I think I'm not alone with that, therefore it might be neat to have an additional filter box "All"/"Pay what you want"/"Free" in the sidebar.

**Comment by MattColville** [comment]
The nice thing about any given record in the database is that none of it ever changes. Temple of Elemental Evil will always be written by Gary Gygax.

If we include pricing info, records will be going out of date all the time and need to be constantly maintained. So, for me, this falls into the "we should be able to expect the user to do a little work on their own," like looking the adventure up when there's no URL, pricing, etc....

**Comment by harkenn** [comment]
Closed as "wont fix" please feel free to continue discussion if you need.
