### ISSUE TITLE
Feature request: high/low magic distinction

### ISSUE THREAD

**Issue by CapBinaryG** [AdventureLookup/AdventureLookup#124]
Will you implement a high/low magic distinction?﻿
I believe this would be a nice addition

**Comment by MattColville** [comment]
Completely sympathize with the desire for a label like this, but this isn't a label publishers have used. So it would be up to the users of the site to develop their own language for this, people wouldn't agree, and even the users would have different ideas about what it meant.

That kind of original research and editorializing is beyond the scope of the site, but I expect folks could include their interpretation of it in a review, when we have reviews.
