### ISSUE TITLE
Enhancement Request: Easier to read Filter Instructions

### ISSUE THREAD

**Issue by cbenist** [AdventureLookup/AdventureLookup#125]
What it says currently:

"Things you type in here will be split at , and then ANDed. Use the filters below for advanced searches (hit the 'Search' button again after filtering)."

Example of what I mean: 

"Search Terms are separated by ',' then combined in a filter "(I assumed this was similar to a database AND may just need to be removed from instructions)

**Comment by burnhamrobertp** [comment]
I think a better phrasing might be `Separate distinct search terms with a comma`?

Otherwise, feel free @ZacharyCauchi
