### ISSUE TITLE
DMs Guild plugin

### ISSUE THREAD

**Issue by aloew** [AdventureLookup/AdventureLookup#126]
If the data can't be mined from DMs Guild (or similar website) directly, I think it would be nice to have a simple browser plugin that autocollects what in can from a given product page. 
It would let you fill in the rest of the missing data points and submit it via the plugin. 

Of course you would have to have also bought the adventure to fill in all the additional information that can only be provided from the book itself and not just the product page, but I think this would enable people to quickly add to the growing library in a fast and easy way.

**Comment by cmfcmf** [comment]
Hi @aloew,
thank you for your proposal! I'm afraid such a plugin is currently out of scope for the project. We can barely handle the amount of bugs/feature requests for the website itself; starting to work on a browser plugin would force use to split the limited forces we have at the moment, which doesn't appear to be feasible. I'm closing this issue for now.
