### ISSUE TITLE
Entering New Publisher Issue

### ISSUE THREAD

**Issue by ShivonQ** [AdventureLookup/AdventureLookup#128]
I was trying to enter a publisher and pressing enter submitted the new adventure instead of letting me add 'Fiery Dragon Productions' to the database.  Just wanted to give you guys a heads up on it!   Keep up the amazing work!

**Comment by ThomasOSB** [comment]
I agree; I was trying to enter an adventure from Avalanche Publishing, who have published several historical campaigns for 3ed, but was unable. I can understand for a one-off company, but if they have produced at least 1/2 dozen, they should be able to be added.

**Comment by cmfcmf** [comment]
"Fiery Dragon" is in the database now. If you want to enter adventures of yet unknown publishers, simply enter it, leave the publisher empty and create a change request on that adventure to add the publisher. 👍 I've also added "Avalanche Publishing".
