### ISSUE TITLE
Unify DM's Guild Listing in "Found In" Field

### ISSUE THREAD

**Issue by Lwnasidh** [AdventureLookup/AdventureLookup#132]
There are currently 46 adventures listed as being found in "Dungeon Master's Guild" and 27 listed in "DMsGuild.com". There are also 26 listed in DriveThruRPG, which may also be a reference to the same place.

**Comment by MattColville** [comment]
I _think_ everything in the DM's Guild is in DriveThruRPG, but the reverse is not true.

But yeah, there should be one entry for DM's Guild.

**Comment by cmfcmf** [comment]
I think we need a *one-click* functionality to allow curators to merge data, i.e. merge all foundIns named *DMsGuild.com* into *Dungeon Master's Guild*.

**Comment by MattColville** [comment]
Yaasssss

**Comment by cmfcmf** [comment]
This kind of stuff can now be done through the new curation panel and has been fixed.
