### ISSUE TITLE
Random Adventure

### ISSUE THREAD

**Issue by MattColville** [AdventureLookup/AdventureLookup#135]
Folks asked for this and I think it's a fun idea. We want to give folks opportunities to spend time on the site and discover new stuff, so an "Spin The Wheel" random adventure button would be fun.

**Comment by WillSave** [comment]
This would be a nice landing page I think for the database. Right now having the entire list show up slows the page down.

**Comment by cmfcmf** [comment]
This was added in #299 and will be live soon.

**Comment by cmfcmf** [comment]
This is now live :tada:
