### ISSUE TITLE
UI is hard to use on a phone

### ISSUE THREAD

**Issue by sethladd** [AdventureLookup/AdventureLookup#139]
Would love to use a mobile friendly version of this. Thanks!

**Comment by harkenn** [comment]
@cmfcmf is that change out on dev yet? @sethladd if it is, check out dev.adventurelookup.com/adventures

**Comment by cmfcmf** [comment]
Hi @sethladd! This has already been fixed by #117 which has been merged and will likely be deployed to the live site over the next couple of days. If you want, checkout the dev site to preview the change: https://dev.adventurelookup.com/adventures/ 
Leaving this issue open until it's live!

**Comment by cmfcmf** [comment]
This is now live at https://adventurelookup.com!
