### ISSUE TITLE
Suggested Adventures

### ISSUE THREAD

**Issue by Daemon53** [AdventureLookup/AdventureLookup#140]
Could we give submitters the ability to recommend other adventures based on the adventure the user is viewing. Kind of like Amazon's "Customers who bought this also bought." Ours could be "These adventures go well with the adventure you are viewing.

**Comment by MattColville** [comment]
Well but what is the use case? If it's part of a series, we have that functionality. If the adventures have enough in common they'll both show up in search results.

**Comment by Daemon53** [comment]
Both are good points. This may be more based on experience. "I have ran this adventure and this other adventure went well with or flowed well with it."

**Comment by MattColville** [comment]
That seems far too editorial and subjective for the site.  Once we have reviews people can include that kind of information  in their review.
