### ISSUE TITLE
Ability to "bookmark" adventures

### ISSUE THREAD

**Issue by kijutsushi** [AdventureLookup/AdventureLookup#141]
It would be nice at some point to have an option to "bookmark" adventures when you're logged in, possibly sorting them into personal lists?

**Comment by cmfcmf** [comment]
Proposal for the a first implementation:
- Each user has a single list of bookmarked adventures.
- A user can bookmark an adventure through a bookmark button on the adventure detail page.

Later, we could go fancy and add multiple (shareable?) lists per user.

**Comment by MattColville** [comment]
Yeah I'd love to see people be able to create multiple lists like adventures I have run, adventures I would like to run. Obviously that's a stretch goal for now

**Comment by jespercockx** [comment]
+1 for user-created lists of adventures. It would be even better if there was also a filter to only search in a specific list.

**Comment by cmfcmf** [comment]
This is now implemented and will soon be available at the live site.
