### ISSUE TITLE
Question: does capitalization matter?

### ISSUE THREAD

**Issue by MattColville** [AdventureLookup/AdventureLookup#143]
Will the system intelligently treat 'boots of speed' as 'Boots of Speed'? By 'intelligently' I mean even if people enter it both ways, you'll only see one on the list of Items?

**Comment by cmfcmf** [comment]
The database has unique constraints on most of the stuff, such as item names, monster names, etc. Users cannot enter 'boots of speed' and 'Boots of Speed', this would throw an error. Whatever is entered first, currently wins.

**Comment by MattColville** [comment]
Ahh, ok, good enough.
