### ISSUE TITLE
Mask Roles on Profile Page

### ISSUE THREAD

**Issue by Daemon53** [AdventureLookup/AdventureLookup#144]
I'm not sure what the other roles look like, but as a User, my role appears as ROLE_USER.  Maybe mask to just say "User"?

![image](https://user-images.githubusercontent.com/5520538/29253533-10e94f44-8045-11e7-8cef-eaef06b200f8.png)

**Comment by cmfcmf** [comment]
This is probably something to tackle when working on #131.

**Comment by harkenn** [comment]
Ideally, each role should map to a displayable value for that role. `ROLE_USER` => `User` which will also handle instances where we might want to change the label `Curator` to => `Moderator` or something in the future. We can adjust the label independently of the role enum
