### ISSUE TITLE
Supplements/Campaign guides/Settings/game accessories?

### ISSUE THREAD

**Issue by aloew** [AdventureLookup/AdventureLookup#147]
I know the site is called adventure lookup, but the system wound lend itself wonderfully for also cataloging the various books that give background information on the various worlds. It's actually the first thing I tried to do with the site.

It would be nice to search for setting [x] Underdark and [x] Supplement for example and find books like Volos guide to the underdark.

**Comment by MattColville** [comment]
I'm sure there is a need for that kind of thing, but it is definitely beyond the scope of the site.
