### ISSUE TITLE
Closing a window to create a new item breaks item editing

### ISSUE THREAD

**Issue by devonjones** [AdventureLookup/AdventureLookup#148]
If I hit the X in the corner instead of saving (say because I noticed a typo), I can't add new items anymore until I leave the page

**Comment by caberlitz** [comment]
I've noticed that it's not specific with the X in the corner, closing it in any way without saving the new item makes me unable to type or add anything inside that field, while able to edit other fields

**Comment by cmfcmf** [comment]
I could reproduce this behaviour.

**Comment by cmfcmf** [comment]
This has been fixed in #187 and will soon be deployed to the live site.
