### ISSUE TITLE
There should be a way to mark basic adventure style

### ISSUE THREAD

**Issue by devonjones** [AdventureLookup/AdventureLookup#149]
Sandbox vs Ordered Narrative

**Comment by devonjones** [comment]
This could be "Is this adventure a sandbox? Unknown/Yes/No"

**Comment by MattColville** [comment]
This would require a lot of interpretation and editorializing and there'd never be consensus among the curators. There's no tradition among adventure publishers for consistently labeling their adventures as such.

Night Below, for instance, begins with a sandbox component, that kind of thing could be handled by the description or comments.
