### ISSUE TITLE
Links to related adventures

### ISSUE THREAD

**Issue by marcellarius** [AdventureLookup/AdventureLookup#150]
An interesting use-case for Adventure Lookup could be discovering related adventures on the site. 

For example, there could be links for:

* The next (and previous?) module in a series
* Reissues of the same adventure for different systems
* Complementary adventures, perhaps set in the same area or offering more detail or background to draw from (this one is more subjective and perhaps not appropriate for AL)

One way this could be implemented would be to have an "add relationship" action (curator only) on an adventure, where you chose a relationship type (next in series, reissue, related), the URL to another adventure on AL, and maybe a comment.  In the database you'd store a table of adventure relationships `(A, relation_type, B)`, which would make them much easier to maintain and query — links wouldn't go stale, you could automatically find the previous module, when adding reissues the server could also add links to the other reissues.

**Comment by MattColville** [comment]
We already have "part of a series." Any other associations would be extremely boutique. Reissues will show up in most searches anyway.

This is another thing I think would be best handled by comments.
