### ISSUE TITLE
There should be a section for recording related resources

### ISSUE THREAD

**Issue by devonjones** [AdventureLookup/AdventureLookup#151]
For example, Burnt Offerings from Rise of the Runelords has:

- A Player's Guide: http://paizo.com/products/btpy8bd9?Pathfinder-Adventure-Path-Rise-of-the-Runelords-Players-Guide
- Paper Pawns: http://paizo.com/products/btpy8tj7?Pathfinder-Pawns-Rise-of-the-Runelords-Pawn-Collection
- A map pack: http://paizo.com/products/btpy91mm?Pathfinder-Adventure-Path-Rise-of-the-Runelords-Anniversary-Edition-Interactive-Maps
- An entire line of miniatures: http://paizo.com/products/btpy8rqs?Pathfinder-Battles-Rise-of-the-Runelords
- Directly uses a flip mat: http://paizo.com/products/btpy8s9x?GameMastery-FlipMat-Town-Square
- Face cards: http://paizo.com/products/btpy8xa0?Pathfinder-Roleplaying-Game-Rise-of-the-Runelords-Face-Cards
- Treasure Cards: 
- Audio: http://paizo.com/products/btpy9el8?Syrinscape-Rise-of-the-Runelords-Mega-SoundPack

There are also supplements that assist specific adventures, such as:
- Varasia, Birthplace of Legends: http://paizo.com/products/btpy8tim?Pathfinder-Player-Companion-Varisia-Birthplace-of-Legends

It would be nice if people could add not just official things that make running a module easier, but if there was also a place where people could add fan created gm tools for that module.

**Comment by devonjones** [comment]
I happen to have run this module, so having access to all this stuff was super useful, but I had to dig.  If this tool is to help GMs find and run adventures, having this kind of information gathered into one place would be invaluable.

**Comment by harkenn** [comment]
I think this would be well handled by Comments, perhaps, especially if comments could be voted upwards for visibility. I'm not sure its ubiquitous enough to warrant a new field.

**Comment by MattColville** [comment]
The site isn't meant to be an all-purpose resource for Dungeon Masters. The power of the site is in its focus.

We can trust people to do a little work on their own, like searching the web for supplementary material. And, as Harkenn said, folks will be able to add comments with links to this stuff in the future.
