### ISSUE TITLE
Feature Request: Sort by price

### ISSUE THREAD

**Issue by EvilVargon** [AdventureLookup/AdventureLookup#152]
It would be nice to be able to sort by free or paid adventures.

**Comment by MattColville** [comment]
This would mean there's one field that's not like all the others; a field that changes over time. As adventures become free, records would become out of date. Nothing else about an adventure ever changes.

I think this would put undue work on the curators and the field would quickly become inaccurate. Also, like a lot of things, I think we can expect the users to do a little work on their own.
