### ISSUE TITLE
Suggestion: Level ranges

### ISSUE THREAD

**Issue by nickgreyden** [AdventureLookup/AdventureLookup#154]
Low 1-6
Med 7-12
High 13-20
Epic 20+

Alternately

Low 1-5
Med 6-10
High 11-15
Very High 16-20
Epic 20+

Easy standardization of level ranges in predictable patterns consistent with benchmarks created by official adventures and player handbooks. I.E. lvl 7+ characters start attracting followers and melee people need to fly/get better ranged. lvl 11+ spells via spell levels and magical items start to get super dangerous and powerful. lvl 15+ armies of low level monsters can't touch players who can, with careful planning, start to level castles with spells and powers.

**Comment by MattColville** [comment]
The problem with that is that not every edition of D&D assumes level 6 is low. Nor that level 10 is medium. 

But, as I said in the video, I think we can rely on the wisdom of crowds and the work of the curators to make sure the level ranges make sense.
