### ISSUE TITLE
Fix the Found In field

### ISSUE THREAD

**Issue by MattColville** [AdventureLookup/AdventureLookup#157]
Currently "Found In" says "The place the adventure can be found in."

WOW that's ambiguous. :D

It should read; "If the adventure is part of a larger product, like a magazine or anthology, list it here."

**Comment by cmfcmf** [comment]
Pull request created in #162, leaving this issue open until the PR is merged and deployed to production.

**Comment by cmfcmf** [comment]
This is now live at https://adventurelookup.com!
