### ISSUE TITLE
"Your Adventures" ceases listing your adventure contributions once you resolve a Change Request

### ISSUE THREAD

**Issue by evansche** [AdventureLookup/AdventureLookup#158]
Been able to duplicate this UI issue: my list of "Your Adventures" on https://adventurelookup.com/profile/ will no lister show adventures the user originates, once they 'resolve' any Change Requests. The adventures missing are still accessible and editable by the user, but just no longer show on https://adventurelookup.com/profile/

**Comment by cmfcmf** [comment]
Hi @evansche, thank you for your bug report!
I've created a pull request in #161 to fix this behaviour. We'll close this issue once it has been merged and deployed to production.

**Comment by cmfcmf** [comment]
This is now live at https://adventurelookup.com!

**Comment by evansche** [comment]
Looks great.
