### ISSUE TITLE
Add 'Has VTT material filter'

### ISSUE THREAD

**Issue by cmfcmf** [AdventureLookup/AdventureLookup#164]
A suggestion I received via email:
> As a suggestion/feature request for Adventure Lookup, can there by an additional search filter for adventures that have materials for virtual tabletops (VTTs) such as fantasy grounds and Roll20? It would be immensely helpful to be able to find those as they are so easy to set up.

**Comment by MattColville** [comment]
Yeah sounds good to me. "VTT Ready" yes/no and the text says "Digital version available for virtual tabletop software."

**Comment by cmfcmf** [comment]
Closing this in favor of #226.
