### ISSUE TITLE
"Invalid credentials"??? log in bug

### ISSUE THREAD

**Issue by JCULindyloo** [AdventureLookup/AdventureLookup#165]
I've added about 5 different adventure and went to add an edit request to another adventure and now I can't log in. There is also no "forgotten password" request available (which would be a good thing anyway).
Is this a server issue?

**Comment by cmfcmf** [comment]
Hi @JCULindyloo,

I'm afraid there currently is not lost password functionality - progress on it is being tracked in #31. There is nothing we can do at the moment. 😕 
I'll be working on #31 now and implement it.

**Comment by JCULindyloo** [comment]
The thing that’s weird is I haven’t forgotten my password. It was even stored in my password database. It just won’t let me in.

Very bizarre.

**Comment by cmfcmf** [comment]
Can you confirm you are using your username, not your email to login?

**Comment by JCULindyloo** [comment]
wow… okay my bad, I’m an idiot :(

**Comment by cmfcmf** [comment]
Nah - happens to me all the time when using my password manager. Closing this then and tracking progress on the lost password functionality in #31.
