### ISSUE TITLE
Request: Should be able to give feedback in the event of an incorrect change request.

### ISSUE THREAD

**Issue by Thedarklordmannimarco** [AdventureLookup/AdventureLookup#167]
IT feels a little weird to click resolve if you dont think the request is valid

**Comment by cmfcmf** [comment]
Hi @Thedarklordmannimarco, you are correct, it currently can be confusing for users to understand why their change request was marked as resolved. The pull request in #169 adds the ability for curators and the adventure's author to add a comment to a change request. Leaving this issue open until it's merged and deployed to the live site!

**Comment by cmfcmf** [comment]
This is now live at https://adventurelookup.com!
