### ISSUE TITLE
Random bugs when creating / editing an adventure

### ISSUE THREAD

**Issue by cmfcmf** [AdventureLookup/AdventureLookup#170]
We have error logging configured at AdventureLookup, I therefore receive emails for 'Server Errors'. I already fixed a few errors, such as the missing length validation issue (#145). However, a few errors are left, which all seem related:

While editing:
- > Call to a member function addAdventure() on null
- > Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO audit_associations (typ, tbl, label, fk, class) VALUES (?, ?, ?, ?, ?)' with params ["app.item", "item", "Sentient Sword", null, "AppBundle\\Entity\\Item"]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'fk' cannot be null"

While creating:
- > Call to a member function setIsUnique() on null
- > Type error: Argument 1 passed to AppBundle\Entity\Adventure::addMonster() must be an instance of AppBundle\Entity\Monster, null given, called in src/AppBundle/Form/AdventureType.php on line 304
- > Type error: Argument 1 passed to AppBundle\Entity\Adventure::addAuthor() must be an instance of AppBundle\Entity\Author, null given, called in src/AppBundle/Form/AdventureType.php on line 304
- > Type error: Argument 1 passed to AppBundle\Entity\Adventure::addItem() must be an instance of AppBundle\Entity\Item, null given, called in src/AppBundle/Form/AdventureType.php on line 304

**Comment by harkenn** [comment]
Some of the `on null` could be Data records that don't align with the ORM definitions (ORM says "not null" but the DB row actually has a null value for that data point). Not sure how exactly Doctrine handles this, but I've seen other ORMs silently fail on the data mapping and return a null.

If that's the case, the "fix" isn't to check for null everywhere, but rather to find the data inconsistencies and address them directly.

This isn't to say that this is definitely the cause, just something I've seen happen before with other ORMs.

**Comment by cmfcmf** [comment]
Should be fixed by #189!
