### ISSUE TITLE
Curators should be able to see a list of change requests

### ISSUE THREAD

**Issue by MattColville** [AdventureLookup/AdventureLookup#173]
I mean, maybe they can, and I just can't find it! :D

But right now as far as I can tell the only way to make progress as a curator is to just fish around the site looking for change requests. Maybe a curator panel with a list of adventures with outstanding change requests?

**Comment by cmfcmf** [comment]
Curators can access a list of change requests using the admin interface at: https://adventurelookup.com/admin/?entity=ChangeRequest&action=list&menuIndex=1&submenuIndex=-1

I agree, however, that the moderation / curation part of the site currently is far from optimal.

**Comment by MattColville** [comment]
I think this should be a priority, as the more we empower the curators, the faster the site gets better.

I mentioned this in #136. 

I'll try to get a video done soon that highlights our developer needs so this isn't all on two people's shoulders.

**Comment by harkenn** [comment]
Admittedly, cmfcmf is doing 99% of all development, so props goes to him for all that.

**Comment by cmfcmf** [comment]
This can now be done through the curation panel.
