### ISSUE TITLE
Sort by entry date

### ISSUE THREAD

**Issue by mmaitlen** [AdventureLookup/AdventureLookup#175]
It'd be nice see the Adventures in the order that they where submitted.  This would be helpful for those of us who'd be willing to review the submissions.  This way, we could see the latest to review.

**Comment by MattColville** [comment]
I think @cmfcmf is working on paginating the front page. It would be nice to have some Sort By options as well.

**Comment by cmfcmf** [comment]
Closing this issue in favor of #179.
