### ISSUE TITLE
Affiliate link logic

### ISSUE THREAD

**Issue by JohnnyFlash** [AdventureLookup/AdventureLookup#177]
We need some affiliate link processing on the purchase links.

I'm imagining the data would go into .yml file maybe parameters.yml

Each entry would have two pieces of data:
URL to match - drivethrurpg.com
Code to add - affiliate_id=1381635

The code would either be added with a ? or & depending on if there are already URL parameters
I think we should also override any existing affiliate data in the submitted URL.

Also, it would be great if we could process all the existing links as we may add new affiliate relationships.

**Comment by cmfcmf** [comment]
I think we shouldn't update the links stored in the database, but rather add affiliate codes whenever the link is displayed on the adventure detail page. That way they can't be overridden by users editing the adventure and we can also change / add new codes on the fly.

**Comment by evansche** [comment]
Dynamic fleshed out links on page rendering makes sense. Some folks, like me, tonight, may scrub off the affiliate parameters in the links thinking we mistakenly left that there from the original entry. Here I am screwing by accident with AL's meager revenue stream!

**Comment by JohnnyFlash** [comment]
Dynamic seems like a good plan.  We will also need a parameter scrubbing system to find links with unnecessary URL params.  Or at least an admin page to find them.

**Comment by JohnnyFlash** [comment]
Knowing that is less of a priority, I am likely to update the database with our affiliate codes where possible.  Even having it on only about 100 entries has already generated some money that we can use to pour back into this project :)  I know I'm creating more work down the line, but I'm confident I can keep the scripts to reverse the process.

**Comment by cmfcmf** [comment]
I will work on implementing this now.
