### ISSUE TITLE
Sort results (by reviews, alphabetically, date of creation, ...)

### ISSUE THREAD

**Issue by ramblindragon** [AdventureLookup/AdventureLookup#179]
Can we have an option to sort our search results alphabetically, and possibly other fields/criteria?

**Comment by cmfcmf** [comment]
> It'd be nice see the Adventures in the order that they where submitted. This would be helpful for those of us who'd be willing to review the submissions. This way, we could see the latest to review.

Merging https://github.com/AdventureLookup/AdventureLookup/issues/175 into this issue.

**Comment by cmfcmf** [comment]
After reviews/ratings (#16) are implemented, another search criterion could be the rating.

**Comment by cmfcmf** [comment]
This is now live :tada:
