### ISSUE TITLE
Include # of Pages in Results List

### ISSUE THREAD

**Issue by WillSave** [AdventureLookup/AdventureLookup#181]
Right now we see readily edition, setting, starting level, environment, and tactical maps. As a DM, I also want to know the time commitment up-front. If we could add just one more to that results plate Pages or something like that, it would help to know how long the adventure is at a glance.

**Comment by cmfcmf** [comment]
That's fair, maybe even remove the 'tactical maps' info. If someone really wants tactical maps, they should use the filter for them.

**Comment by WillSave** [comment]
Sure if there is not enough room for a sixth item in the results maybe that is the lowest hanging fruit, but there is room for six items, I would say keep it in. 

On second thought, if Matt's interpretation of "tactical map" is in fact _tactile_ map, that is, a fold out map to put on the table that has 1" battle squares, then tactical map would be so rarely used maybe it could be dropped off the results list. However, I have seen many _USER entries giving this a "Yes" value simply if there are in fact _tactical_ maps, that is, maps in the text the DM can use to figure out combat/exploration. Maybe this has drifted into a new thread though.

**Comment by cmfcmf** [comment]
This is now fixed and will soon be deployed to the live site. Tactical maps were indeed intended to be battle mats, which has also been fixed.
