### ISSUE TITLE
Add 'Indie Dev' to Publisher list

### ISSUE THREAD

**Issue by notklaatu** [AdventureLookup/AdventureLookup#184]
On twitter, I asked @MattColville how indie titles should be added.  He responded:

    I think folks who publish their own stuff on the DM's Guild should be listed on adventure lookup as Indie
    Dev. One broad category.

https://twitter.com/mattcolville/status/896810286123855872

As with my previous bug report, I'm not sure this is the right place to request DB additions, so sorry if this is misplaced.

**Comment by cmfcmf** [comment]
*Indie Dev.* publisher added! 
Don't worry about where to post the it. The advantage of GitHub is that requests don't get lost in the depths of the internet, because you can clearly see which issues are open and which are closed.
