### ISSUE TITLE
Add "issue number" field

### ISSUE THREAD

**Issue by marcellarius** [AdventureLookup/AdventureLookup#185]
Dungeon Magazine has made a mess of the "Found In" field, and listing each issue as a separate entry makes it infeasible to search the entire magazine.

This could be solved by adding a separate "Issue number" field.

**Comment by MattColville** [comment]
Not a bad idea. I think some fields need their own search field anyway, because the number of entities is so large. That would solve a lot of problems.

**Comment by cmfcmf** [comment]
> Not a bad idea. I think some fields need their own search field anyway, because the number of entities is so large. That would solve a lot of problems.

This is now fixed! All filters have their own separate search fields.

> Dungeon Magazine has made a mess of the "Found In" field, and listing each issue as a separate entry makes it infeasible to search the entire magazine.

It is now easier than ever to see all 'Dungeon Magazine' adventures:

![dungeon magazine](https://user-images.githubusercontent.com/2145092/85222479-9e0b0500-b3bb-11ea-9a43-64d9fe190642.gif)

I am also working on the ability to search for exact phrases in the freetext search bar at the top of the page. Once that's working, searching for `"Dungeon Magazine"` (note the quotation marks) will be an even easier way to find all 'Dungeon Magazine #XYZ' adventures. The same is true for 'Dragon Magazine', of course.

Given these changes, I don't think there is still need for an 'issue number' field.
