### ISSUE TITLE
Expand URL shorteners before storing links in database

### ISSUE THREAD

**Issue by JohnnyFlash** [AdventureLookup/AdventureLookup#186]
I just came across a bit.ly link which was hiding an affiliate link.  If we are to use our own links, we will need to process url shorteners.

**Comment by cmfcmf** [comment]
This needs to be done carefully, for the same reasons as described in https://github.com/AdventureLookup/AdventureLookup/issues/84#issuecomment-318463729.

**Comment by cmfcmf** [comment]
The most common url shorteners are now blocked. Curators can add additional domains to the block list at https://adventurelookup.com/curation/domains.
