### ISSUE TITLE
Making edits on an iPad?

### ISSUE THREAD

**Issue by hangarflying** [AdventureLookup/AdventureLookup#192]
Perhaps I am illiterate on how to make corrections, but I don't seem to be able to make any edits to comply with change requests.

Clicking "Edit" just edits the change request, and clinking on the adventure links brings up a page with fields that I can't change.

Is editing to be done on PC only?

Thanks.

**Comment by harkenn** [comment]
Editing can only be done if you are a `Curator` or if the adventure in question was originally submitted by you (I think? this one might not be true anymore either).

**Comment by hangarflying** [comment]
I thought I was. I have an admin tab.

I can open other people's entries to edit them, but opening anything through the change request doesn't allow me to edit that.

**Comment by harkenn** [comment]
The "Edit" button next to the change request is purely that, you're editing the change request.

Editing an adventure requires you to go into the admin panel by clicking "Admin" at the top of your screen.

**Comment by hangarflying** [comment]
That's what I'm saying: I can't make edits. Is this because it's an iPad thing, or am I not doing something right?

**Comment by harkenn** [comment]
You're not able to make edits from within the Admin panel, am I understanding you correctly?

I can't speak to iPads in particular. Have you tried from any sort of computer?

**Comment by MattColville** [comment]
When logged in, do you see a button on each adventure that says "edit adventure?" It's about halfway down the page above a big red button marked DELETE.

**Comment by Wigginns** [comment]
Works fine as of today. Closing this issue.
