### ISSUE TITLE
Add "tags" field

### ISSUE THREAD

**Issue by marcellarius** [AdventureLookup/AdventureLookup#193]
This was suggested by [melinate over on /r/AdventureLookup](https://www.reddit.com/r/AdventureLookup/comments/6tok96/should_we_identify_traps_as_a_common_monster/dlmjmkr/)

This mechanism should be simple to add, and would cover a wide array of categorisation tasks. E.g.

* Adventure types: Mystery, Funhouse, Sandbox
* Mythology/theme: Norse, Greek, Celtic, Eastern, Gothic
* Prominent elements: Traps, Riddles, Social interaction
* 'Utility' tags: Short, Soloable, Scalable

**Comment by cmfcmf** [comment]
[/u/marcellarius also suggested](https://www.reddit.com/r/AdventureLookup/comments/6tok96/should_we_identify_traps_as_a_common_monster/dln1i35/) that editing the list of available tags should be a curator-only feature.

**Comment by cmfcmf** [comment]
Closing this in favor of #289.
