### ISSUE TITLE
Edition Conversion Supplements?

### ISSUE THREAD

**Issue by vennlar** [AdventureLookup/AdventureLookup#195]
Should links/tags be included for edition conversion supplements for certain adventures? Or should/can the supplement be uploaded as it's own adventure?

I was looking at an AD&D adventure (I1 Dwellers of the Forbidden City) and in the comments of the RPGNow purchase page people mentioned that there is a 5e conversion supplement on the DM's Guild. So there is a way for a 5e DMs to play this AD&D Adventure without having to manually convert. Conversion is something that not all DMs are comfortable doing on their own and if there are other supplements like these then it would open up the options for newer/less comfortable DMs to choose from.

**Comment by cmfcmf** [comment]
The current approach is to list a separate adventure for every edition.
