### ISSUE TITLE
Filter by notable locations?

### ISSUE THREAD

**Issue by tyson-nw** [AdventureLookup/AdventureLookup#198]
If I want to find all the adventures that take place in Baldur's Gate, Waterdeep, or Menzoberranzan would be useful.  I tried searching for adventures that mention Baldur's Gate and the results were less than useful, returning adventures with "gate" or "investigate" in their description or mentioning Baldur's gate offhand.

Search terms attempted, limited by Forgotten Realms setting filter:
* Baldur
* Baldur's
* Baldur's AND Gate
* "Baldur's Gate"

**Comment by cmfcmf** [comment]
I know this is a late response, sorry.
The search term you were looking for is `Baldur's, Gate`. Yup, it's confusing. All your other attempts were implicitly searching for `Baldur's OR Gate`.

For more context, I'll quote my [response in the other issue](https://github.com/AdventureLookup/AdventureLookup/issues/280#issuecomment-629217790):
> This is the expected (albeit confusing) behavior. By default, terms are combined with OR (e.g., searching for `sandbox roleplay` returns adventures that contain both terms or just one of the terms). Searching for `sandbox, roleplay` causes the terms to be ANDed, resulting only in adventures which contain both terms.
>
> Since this is behavior is quite confusing, I changed it in #308, which will soon go live on adventurelookup.com. It then works like this:
> - searching for 'sandbox roleplay' results in adventures that contain both terms
> - searching for 'sandbox OR roleplay' results in adventures that contain both terms, then those that contain just one of the terms.

**Comment by cmfcmf** [comment]
This is now live :tada: 

Searching for `Baldur's Gate` now returns the expected results.
