### ISSUE TITLE
Duplicate list items

### ISSUE THREAD

**Issue by calculuschild** [AdventureLookup/AdventureLookup#200]
The search bar might treat "goblin" and "goblins" the same, but we have two separate entries in the common monsters list for "goblin" and "goblins." I think the same goes for a few other species on there.

**Comment by cmfcmf** [comment]
Hi @calculuschild,
the problem with these duplicates is that currently there isn't any *bulk-update all "goblins" to "goblin"* functionality. Once such a functionality is implemented (start is in #202), we can go ahead and unify these duplications.

**Comment by cmfcmf** [comment]
Fixed this particular issue using the new curation panel.

**Comment by calculuschild** [comment]
There are still several other duplicated cases. What would be the best way to report them? Here? Through a change request on the website? Reddit?

**Comment by cmfcmf** [comment]
I think either way works well. 👍

**Comment by calculuschild** [comment]
In that case:

Animated Object - Animated Objects
Bat - Common Bats
Cultist - Cultists
Demons - Daemon - Demons
Devil - Devils
Djinn - Djinni
Elemental - Elementals
Ooze - Oozes
Orc - Orcs
Snake - Snakes
Stirge - Stirges
Swarm of Insects - Swarm of Insects (Centipedes) - Centipede (not sure what to do here)
Wolf - Wolves

I probably missed some. But I also wonder if there is a defined standard for monsters being listed as singular or plural. For instance we have "Half-ogre", but "Half-orcs".

**Comment by calculuschild** [comment]
I would also mention that both "goblin" and "goblins" show up as possible monsters when adding them to an adventure. Somebody adding a new adventure might select "goblins" from the list and now we have the problem all over again.

**Comment by cmfcmf** [comment]
> I would also mention that both "goblin" and "goblins" show up as possible monsters when adding them to an adventure. Somebody adding a new adventure might select "goblins" from the list and now we have the problem all over again.

Whoops! I figured out why: Goblins was indeed being replaced by goblin for all adventures, but a monster entry for goblins still remained in the database. Although that entry had no adventures associated with it, it is suggested when creating a new adventure. I've fixed this in #220. I'll work on your list once that's merged and deployed. Thanks!

**Comment by cmfcmf** [comment]
I've now gone through your list @calculuschild and removed the plural forms.
