### ISSUE TITLE
Request: Filter by adventure focus

### ISSUE THREAD

**Issue by Asgroth** [AdventureLookup/AdventureLookup#207]
What do you think of a filter to find adventures mostly based on combat vs social vs exploration vs mystery vs all-rounder?

I DM for groups with different tastes, a group of mostly girls prefers the social intrigue of courts and politics, while another group is more dungeon-delve minded.

**Comment by durnin** [comment]
I was thinking about this one too but with a slightly different approach, like having not one field many fields: "combat", "social", "exploration", "investigation/puzzle" and give a category value for each of these, like "none", "few", "some", "a lot", etc. or similar.

**Comment by cmfcmf** [comment]
I'll close this issue in favor of https://github.com/AdventureLookup/AdventureLookup/issues/289, which is really similar and has even more info.
