### ISSUE TITLE
Search by Author bringing up incorrect results

### ISSUE THREAD

**Issue by calculuschild** [AdventureLookup/AdventureLookup#210]
To be clear, I know we don't have a normal "Search by Author" field on the front page. This is fine, and I'm not proposing to change that.

So I'm looking at the details of an adventure, and click the little magnifying glass next to the author name, and I get a page with a list of other adventures by that author. For example, some adventures by "Dan Coleman": [https://www.adventurelookup.com/adventures/?f%5Bauthors%5D%5Bv%5D=Dan%20Coleman](https://www.adventurelookup.com/adventures/?f%5Bauthors%5D%5Bv%5D=Dan%20Coleman)

All is well, until I click the "Load More Results" button. Suddenly we have a whole bunch of random other adventures not written by "Dan Coleman." This doesn't seem to be working as it should.

**Comment by harkenn** [comment]
"Load More Results" probably shouldn't show when filtering in this way. Not sure if this is reproducible using any of the standard (available on left side) filters, or not.

**Comment by calculuschild** [comment]
At least for "Common Monsters", what happens is clicking "Load More Results" will simply show an error saying "We're sorry. Apparently there is no adventure matching your search :("

In that case it still probably shouldn't show the "Load More Results" button if there aren't actually any more results, but at least it's not adding invalid results like it does with authors.

I haven't tested any other fields.

**Comment by cmfcmf** [comment]
I think I know what's going on.
