### ISSUE TITLE
Next Master Merge?

### ISSUE THREAD

**Issue by JohnnyFlash** [AdventureLookup/AdventureLookup#211]
How are we looking for the next production update?

**Comment by cmfcmf** [comment]
We can do so any time - I've just created a pull request for it: https://github.com/AdventureLookup/AdventureLookup/pull/213, but I'd like to get #212 merged first.

**Comment by harkenn** [comment]
Merged

**Comment by JohnnyFlash** [comment]
With this update, should I be able to remove the hard-coded affiliate links and have them still work?

**Comment by cmfcmf** [comment]
Yes. Feel free to do a test on a single adventure first. 
Also make sure to `php bin/console cache:clear` if you make changes to the `parameters.yml` file to add the affiliate mappings.
