### ISSUE TITLE
Feature Request - Adventure Code

### ISSUE THREAD

**Issue by bmfrosty** [AdventureLookup/AdventureLookup#214]
Feature request is to add a field for Adventure Code - This is probably better than doing double duty with the Title field.

**Comment by marcellarius** [comment]
Adding a separate field would be considerably more effort than it's worth, especially with >1000 adventures in the database and many of the TSR modules already added. 

Searching for modules by code currently works well, it's consistent with sites like dmsguild do it, and not all modules have a meaningful code. 

Is there a specific use-case for having the code as a separate field?

**Comment by bmfrosty** [comment]
It was just a suggestion.

**Comment by cmfcmf** [comment]
Hey @bmfrosty, thank you for your input!
I'll close this for the reasons @marcellarius provided.
