### ISSUE TITLE
Feature Suggestion: Module name in HTML/tab title. 

### ISSUE THREAD

**Issue by Collie4o3** [AdventureLookup/AdventureLookup#215]
he html title for each page at the moment is just "Adventure Lookup" if we prepended the adventure name so it was "Curse of Strahd - Adventure Lookup" it would be easier to identify the tab you wanted if you had several adventurers open.
This has the added benefit of changing the title of any bookmarks made to include the adventure name.
Depending on when adventure information is loaded this could either be a trivial or more complex task. Hopefully you should just use a PHP variable on load that is provided by the backend.

**Comment by Collie4o3** [comment]
I might look into forking the code and implementing it myself, but I am a little strapped for time running two campaigns and working full time.

**Comment by Collie4o3** [comment]
I see now that the document title is managed by the react package 'react-title-component' it looks like this includes handling for what I suggested.

**Comment by cmfcmf** [comment]
Hey @Collie4o3, thank you for your valid and good suggestion!
I'm afraid though that you were looking at the _outdated_ and not-in-user `adventurelookup-frontend` repository. This is part of an older attempt to develop adventure lookup. All code of adventure lookup is located inside this repository (https://github.com/AdventureLookup/AdventureLookup).
The title is set here: https://github.com/AdventureLookup/AdventureLookup/blob/dev/app/Resources/views/base.html.twig#L6 and can be overridden by overriding the title block in a child template.

**Comment by Collie4o3** [comment]
I realised I was looking at an old repo earlier today. I hadn't had a chance to attempt it in earnest yet fortunately.
