### ISSUE TITLE
Feature request: Admin Panel should show foundIn and partOf records

### ISSUE THREAD

**Issue by evansche** [AdventureLookup/AdventureLookup#216]
I'm a curator, and through the Admin Panel occasionally I'd like to review and touch-up entries for the various foundIn and partOf records. But I cannot see these in the Admin Panel. Please add these?

**Comment by cmfcmf** [comment]
This is a valid request - I have already implemented a feature which allows you to see them. It will be live once @JohnnyFlash updates the production server. Here's a preview from the dev server:
![image](https://user-images.githubusercontent.com/2145092/29686610-eec044e4-8919-11e7-9063-7b40851cf780.png)
There is a dropdown with all the values and below that (not visible in screenshot) another dropdown which allows you to easily replace all occurrences of value A by value B.

**Comment by cmfcmf** [comment]
The curation panel is now live - feel free to leave any further feedback comments! If you don't have any, close the issue.

**Comment by evansche** [comment]
Very cool! I just briefly checked it out on mobile, and I'll take a deeper dive from a PC sooner or later.

**Comment by cmfcmf** [comment]
Closing this for now. If you find an issue, feel free to leave your comment.

**Comment by evansche** [comment]
Yup, this works. I have been using the new bulk-edit of foundIn entries to clean up missing capitalization for "dungeon magazine" and removing some errant pointers there which are better found in links or the publisher field.
