### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by fictionalbeing** [AdventureLookup/AdventureLookup#217]
As of 8.25.17 Get this error when clicking on any entry

Oops! An Error Occurred

The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by JohnnyFlash** [comment]
`INFO

Message:	
Matched route "adventure_show".
Time:	
2017-08-25 16:37:02
Channel:	
request
Context:	
route:	
adventure_show
route_parameters:	
{
    "_controller": "AppBundle\\Controller\\AdventureController::showAction",
    "slug": "trapped-in-the-toybox",
    "_route": "adventure_show"
}
request_uri:	
https://www.adventurelookup.com/adventures/trapped-in-the-toybox
method:	
GET
INFO

Message:	
Populated the TokenStorage with an anonymous Token.
Time:	
2017-08-25 16:37:02
Channel:	
security
CRITICAL

Message:	
Undefined class constant 'HEADER_X_FORWARDED_FOR'
Time:	
2017-08-25 16:37:02
Channel:	
php
Context:	
exception:	
{
    "class": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
    "message": "Undefined class constant 'HEADER_X_FORWARDED_FOR'",
    "code": 0,
    "file": "/var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Fragment/InlineFragmentRenderer.php:122",
    "trace": [
        "/var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Fragment/InlineFragmentRenderer.php:76",
        "/var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Fragment/FragmentHandler.php:91",
        "/var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/LazyLoadingFragmentHandler.php:79",
        "/var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Extension/HttpKernelRuntime.php:46",
        "/var/www/new.adventurelookup.com/html/var/cache/prod/twig/b6/b6fd837935e64c0ddad76929ccbe97ed6c28f6aea1bf59eae6ae61cb99439792.php:443",
        "/var/www/new.adventurelookup.com/html/vendor/twig/twig/lib/Twig/Template.php:188",
        "/var/www/new.adventurelookup.com/html/var/cache/prod/twig/4c/4c6347d5c047edacb2f5603350408b74aa31eedb9efb8d3dcd799198080c7401.php:218",
        "/var/www/new.adventurelookup.com/html/vendor/twig/twig/lib/Twig/Template.php:389",
        "/var/www/new.adventurelookup.com/html/vendor/twig/twig/lib/Twig/Template.php:366",
        "/var/www/new.adventurelookup.com/html/var/cache/prod/twig/b6/b6fd837935e64c0ddad76929ccbe97ed6c28f6aea1bf59eae6ae61cb99439792.php:24",
        "/var/www/new.adventurelookup.com/html/vendor/twig/twig/lib/Twig/Template.php:389",
        "/var/www/new.adventurelookup.com/html/vendor/twig/twig/lib/Twig/Template.php:366",
        "/var/www/new.adventurelookup.com/html/vendor/twig/twig/lib/Twig/Template.php:374",
        "/var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Bridge/Twig/TwigEngine.php:49",
        "/var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/TwigEngine.php:45",
        "/var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/TwigEngine.php:72",
        "/var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerTrait.php:234",
        "/var/www/new.adventurelookup.com/html/src/AppBundle/Controller/AdventureController.php:105",
        "{\"function\":\"showAction\",\"class\":\"AppBundle\\\\Controller\\\\AdventureController\",\"type\":\"->\",\"args\":[\"[object] (AppBundle\\\\Entity\\\\Adventure: Trapped in the Toybox)\"]}",
        "/var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:153",
        "/var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68",
        "/var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:171",
        "/var/www/new.adventurelookup.com/html/web/app.php:15"
    ]
}
CRITICAL

Message:	
Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Undefined class constant 'HEADER_X_FORWARDED_FOR'" at /var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Fragment/InlineFragmentRenderer.php line 122
Time:	
2017-08-25 16:37:02
Channel:	
request
Context:	
exception:	
{
    "class": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
    "message": "Undefined class constant 'HEADER_X_FORWARDED_FOR'",
    "code": 0,
    "file": "/var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Fragment/InlineFragmentRenderer.php:122",
    "trace": [
        "/var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Fragment/InlineFragmentRenderer.php:76",
        "/var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Fragment/FragmentHandler.php:91",
        "/var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/LazyLoadingFragmentHandler.php:79",
        "/var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Extension/HttpKernelRuntime.php:46",
        "/var/www/new.adventurelookup.com/html/var/cache/prod/twig/b6/b6fd837935e64c0ddad76929ccbe97ed6c28f6aea1bf59eae6ae61cb99439792.php:443",
        "/var/www/new.adventurelookup.com/html/vendor/twig/twig/lib/Twig/Template.php:188",
        "/var/www/new.adventurelookup.com/html/var/cache/prod/twig/4c/4c6347d5c047edacb2f5603350408b74aa31eedb9efb8d3dcd799198080c7401.php:218",
        "/var/www/new.adventurelookup.com/html/vendor/twig/twig/lib/Twig/Template.php:389",
        "/var/www/new.adventurelookup.com/html/vendor/twig/twig/lib/Twig/Template.php:366",
        "/var/www/new.adventurelookup.com/html/var/cache/prod/twig/b6/b6fd837935e64c0ddad76929ccbe97ed6c28f6aea1bf59eae6ae61cb99439792.php:24",
        "/var/www/new.adventurelookup.com/html/vendor/twig/twig/lib/Twig/Template.php:389",
        "/var/www/new.adventurelookup.com/html/vendor/twig/twig/lib/Twig/Template.php:366",
        "/var/www/new.adventurelookup.com/html/vendor/twig/twig/lib/Twig/Template.php:374",
        "/var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Bridge/Twig/TwigEngine.php:49",
        "/var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/TwigEngine.php:45",
        "/var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/TwigEngine.php:72",
        "/var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerTrait.php:234",
        "/var/www/new.adventurelookup.com/html/src/AppBundle/Controller/AdventureController.php:105",
        "{\"function\":\"showAction\",\"class\":\"AppBundle\\\\Controller\\\\AdventureController\",\"type\":\"->\",\"args\":[\"[object] (AppBundle\\\\Entity\\\\Adventure: Trapped in the Toybox)\"]}",
        "/var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:153",
        "/var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68",
        "/var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:171",
        "/var/www/new.adventurelookup.com/html/web/app.php:15"
    ]
}`

**Comment by cmfcmf** [comment]
You need to execute `rm var/bootstrap.php.cache` like described in the PR.

**Comment by JohnnyFlash** [comment]
ME :gun:

**Comment by cmfcmf** [comment]
Thanks @JohnnyFlash! And sorry for the hassle caused by this 😕
