### ISSUE TITLE
Field for module index number / code [New Field]

### ISSUE THREAD

**Issue by notklaatu** [AdventureLookup/AdventureLookup#219]
TSR modules, and many others, have module code numbers. For example, ``HHQ3 Thief's Challenge`` or ``RM3 Web of Illusion`` and so on. It seems that a convention has surfaced, but it would be easier if there was a field for it so that the title line could contain the title, and only the title.

Ref: https://www.reddit.com/r/AdventureLookup/comments/6vanai/module_code_in_the_title/

**Comment by marcellarius** [comment]
Issue #214 made this suggestion too, and @cmfcmf decided not to implement it.

I agree in principle that it should have a separate field, but in practice it would just mean that the software would have to concatenate them wherever it rendered a title, in the text search index etc. Given that ElasticSearch does a good job of finding modules by their code as is, there isn't an immediate need for a separate field.

But having a separate field would add options for how the adventures are displayed, for example:

### Thief's Challenge ###
*HHQ3 - Head-to-Head Quests series*

**Comment by notklaatu** [comment]
Apologies, I didn't notice the issue had been raised.

The adventures I've submitted have had several change reqs filed based on the module number and where and how it is placed in the title, but I guess it's mainly just an aesthetic thing. Hat tip to ElasticSearch.
