### ISSUE TITLE
Resolved Issue Archive

### ISSUE THREAD

**Issue by WillSave** [AdventureLookup/AdventureLookup#223]
I submitted a few enhancements to a few modules. Over time they each dropped out of my profile history--presumably resolved but since I can't remember exactly which module and what I asked, it is tough to discover what action (if any) was actually done. It would be nice to still be able to see when someone has resolved an issue with a module. I would like to have breadcrumbs back to the issues themselves to check to see what changes were made.

**Comment by cmfcmf** [comment]
Hey @WillSave, I know it's been a while, but I finally managed to implement your suggestion. I've included a screen shot in the pull request: https://github.com/AdventureLookup/AdventureLookup/pull/274
