### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by martixy** [AdventureLookup/AdventureLookup#227]
I was watching Matt's latest video and he mentioned AdventureLookup and this repo,

Incidentally the technologies he mentioned is precisely the dev stack I'm currently working with.

So, ya need any help?

(Currently setting up the project with me. One question I have is - what's the SSH password for the vagrant. Another suggestion is - I'm on windows and there is a vagrant plugin for windows for NFS that works brilliantly, that would probably improve performance significantly. It also helps with the symlinks composer wants to create.)

**Comment by burnhamrobertp** [comment]
Once you `vagrant up` you can `vagrant ssh` to get into the box. Feel free to add the plugin to the vagrantfile.

**Comment by martixy** [comment]
I wanted to use putty, you know. :)

**Comment by martixy** [comment]
Project setup's iffy though.

- Had to install composer manually.
- Fixtures won't load.
- Couldn't get the webpack dev-server to work.

I'll finish setup another day. Went through some of the issues, not very many of them are worth pursuing as I see it.

**Comment by burnhamrobertp** [comment]
the fixtures have to be run from inside the vagrant box, and the webpack npm script commands need to be run from outside of the vagrant box.

**Comment by burnhamrobertp** [comment]
We would love to have additional contributors. If you continue to have trouble let me know and I'll be happy to help out.
