### ISSUE TITLE
Sign On Error

### ISSUE THREAD

**Issue by hobk1ard** [AdventureLookup/AdventureLookup#234]
Is anyone else unable to sign on? 

I created me account on Tuesday and I was able to sign on just fine and add a few adventures. Wednesday morning, I needed to sign in again and I got the "Invalid credentials" error. Odd, I use Lastpass so unlikely, but I reset my password and tried again. Same result.

I have since reset my password 4 or 5 times using different length and complexity of password and I still cannot sign in.

**Comment by cmfcmf** [comment]
Hey @hobk1ard,

could you please confirm you are using your *username*, not your email address, to sign in?

**Comment by hobk1ard** [comment]
Well, don't I feel stupid. I didn't even question the autofill using the email address.

**Comment by cmfcmf** [comment]
No worries, you are [not the first one](https://github.com/AdventureLookup/AdventureLookup/issues/165). I'm glad it works now!
