### ISSUE TITLE
Dungeon & Dragon Magazine

### ISSUE THREAD

**Issue by TheWesUber** [AdventureLookup/AdventureLookup#238]
It is possible to make a single found in category for each Dungeon Magazine and Dragon Magazine and a subcategory for individual issues? It seems it would be easier for the user to sort and find that way.

**Comment by calculuschild** [comment]
Yep, we need some kind of nested tree structure in the search categories. Not just for this, but for monsters and probably some other categories as well. As it is it's too hard for a user to sift through giant lists to find the checkbox he wants.

**Comment by cmfcmf** [comment]
Hi!
The updated filter sidebar now makes it easier than ever to see all 'Dungeon Magazine' adventures:

![dungeon magazine](https://user-images.githubusercontent.com/2145092/85222479-9e0b0500-b3bb-11ea-9a43-64d9fe190642.gif)

I am also working on the ability to search for exact phrases in the freetext search bar at the top of the page. Once that's working, searching for `"Dungeon Magazine"` (note the quotation marks) will be an even easier way to find all 'Dungeon Magazine #XYZ' adventures. The same is true for 'Dragon Magazine', of course.

Given these changes, I don't think there is still need for an 'issue number' field.

**Comment by calculuschild** [comment]
I notice in the demo gif the results are out of numerical order. Is there a way to change that so it looks more organized?

**Comment by cmfcmf** [comment]
That's a very good point! I implemented it in #374.
