### ISSUE TITLE
When I try to log in it says i have invalid credentials even if i know they're correct

### ISSUE THREAD

**Issue by amedaus** [AdventureLookup/AdventureLookup#239]

**Comment by burnhamrobertp** [comment]
At this time there are no widespread issues pertaining to logging in. Please remember that AL's login system uses a `username` and not an `email`. If you have forgotten your login credentials, please go [here](https://adventurelookup.com/reset-password/request) to reset it using your email.

To be clear, the reset process uses your e-mail. The login process uses your username.
