### ISSUE TITLE
#Devs Vagrant issues: Maybe fixes and whatnot

### ISSUE THREAD

**Issue by gn000we** [AdventureLookup/AdventureLookup#245]
I'm not sure what happened to my vagrant virtualbox (as per the instructions to setup) but virtualbox took a lot of my computer's resources as well as not working, and having lots of errors, lag etc. 
I did it manually using VMPlayer and ran through all the vagrant commands.

I noticed:
1) I had to installed "curl" because the the "curl" command to get the nodejs source errored (as a dependency requirement).
2) trying to run the "curl" command, post install of "curl", to get the nodejs source, error-ed due to a locked pkgcache.bin etc. This might be the reminisce of the previous error-ed running of the "curl" command.
3) the "composer.php" downloaded from the command (and online) has a different hash (probably due to being a newer, updated file).
4) even with the newer file, I still encountered problems/errors with the script.
5) I had to download the AdventureLookup (my fork),` chown -R` my user's local `~/.composer` folder to my `user:user` and I also had to run this
`echo "{}" > ~/.composer/composer.json`
6) I downloaded the "composer.phar" file instead and then moved this to the AdventureLookup code folder and ran it there with...
`php composer.phar --working-dir=/home/myuser/github/AdventureLookup --vvv --ansi about`
to test. 
7) I have also run `php composer.phar --working-dir=/home/myuser/github/AdventureLookup --vvv --ansi update`
After updates/installs/etc. I had to specify parameters at the end (port `3306` for the MySQL database, all others default, except "secret". I recommend creating a secret passphrase in the Ubuntu "Password and keys" app and then using that).

Please note: The above has been done in a development VM environment and not a plain, dependant workstation/production server etc. The commands used and scripts used are probably not that secure (esp. the "chown").

**Comment by burnhamrobertp** [comment]
What are your hardware's specs, just for my own curiosity, that virtualbox was giving you trouble?

**Comment by gn000we** [comment]
8gb ram, 2ghz.
