### ISSUE TITLE
#Devs Missing ~/web/assets/manifest.json? default generated after webpack-dev-server run

### ISSUE THREAD

**Issue by gn000we** [AdventureLookup/AdventureLookup#246]
All looks ok. Loaded and installed in my manual vm instance.
On running the webpack-dev-server, looks like it generates a default json.

**Comment by burnhamrobertp** [comment]
The missing manifest file is an error you'll see anytime the front end is not building correctly or was only partially built at the time of the page load. If - for example - you make a change to a webpack-watched file and then quickly try to refresh your page, you might see the manifest error as webpack hasn't finished at the time you refreshed your browser.
