### ISSUE TITLE
Server Upgrade Doc

### ISSUE THREAD

**Issue by JohnnyFlash** [AdventureLookup/AdventureLookup#25]
As you guys are using tech I'm not very familiar with,  I would appreciate a list of commands that you recommend I do whenever I pull from GitHub to the server.

**Comment by harkenn** [comment]
`composer install --no-dev --optimize-autoloader`
`npm run prod`

**Comment by JohnnyFlash** [comment]
That didn't work :(

Something went horribly wrong...

`Generating optimized autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "SensioGeneratorBundle" from namespace "Sensio\Bundle\GeneratorBundle".
Did you forget a "use" statement for another namespace? in /var/www/new.adventurelookup.com/html/app/AppKernel.php:28
Stack trace:
#0 /var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(406): AppKernel->registerBundles()
#1 /var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(113): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(137): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(124): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
#4 /var/www/new.adventurelookup.com/html/ve in /var/www/new.adventurelookup.com/html/app/AppKernel.php on line 28
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the symfony-scripts event terminated with an exception


  [RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command:
  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load c
  lass "SensioGeneratorBundle" from namespace "Sensio\Bundle\GeneratorBundle".
  Did you forget a "use" statement for another namespace? in /var/www/new.adventurelookup.com/html/app/App
  Kernel.php:28
  Stack trace:
  #0 /var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.
  php(406): AppKernel->registerBundles()
  #1 /var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.
  php(113): Symfony\Component\HttpKernel\Kernel->initializeBundles()
  #2 /var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Conso
  le/Application.php(137): Symfony\Component\HttpKernel\Kernel->boot()
  #3 /var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Conso
  le/Application.php(124): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
  #4 /var/www/new.adventurelookup.com/html/ve in /var/www/new.adventurelookup.com/html/app/AppKernel.php o
  n line 28
`

**Comment by MattColville** [comment]
I don't know what any of that means, but it looks bad.

**Comment by cmfcmf** [comment]
Don't worry! This should work: 
```
composer install --optimize-autoloader
```

**Comment by JohnnyFlash** [comment]
Now this :(

Key "14" for array with keys "73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 90" does not exist.
500 Internal Server Error - Twig_Error_Runtime

**Comment by cmfcmf** [comment]
Can you post the output of the 
```
export SYMFONY_ENV=prod 
php bin/console cache:clear
``` 
command?

**Comment by JohnnyFlash** [comment]
root@AdvLookup:/var/www/new.adventurelookup.com/html# export SYMFONY_ENV=prod
root@AdvLookup:/var/www/new.adventurelookup.com/html# php bin/console cache:clear

 // Clearing the cache for the prod environment with debug false


 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.

**Comment by cmfcmf** [comment]
Ah. I see. It's due to bugs added over the night. The code is currently not able to be run. It would be best to git reset to a working version, i.e. 4c2a41212d0e2347a521412eeda4268b63b2e3cf

**Comment by JohnnyFlash** [comment]
Damn bugs... OK... I'll leave the live version here until you guys say the HEAD is stable again.

**Comment by cmfcmf** [comment]
Perfect 👍 I will go through the discussions now and add some comments. A working HEAD should be available soon :)

**Comment by cmfcmf** [comment]
An update script has been added to the repository. It must be called like this with the application's root directory as current working directory:
```bash
$ ./scripts/update.sh
```
This will pull new changes and execute necessary commands, such as updating dependencies or applying migrations.
