### ISSUE TITLE
Guide new contributors better

### ISSUE THREAD

**Issue by cmfcmf** [AdventureLookup/AdventureLookup#250]
The should be documentation on how to get started, how to pick an issue, how the review/merge process works etc. to simplify onboarding of new contributors
> i'm interested in helping out. is there something like a CONTRIBUTORS.md or a section in the readme that i'm missing? do you work with forks or do you add people to the original repo? if i wanna work on something, do i ask you to assign an issue to me or how's that handled?

**Comment by j-frost** [comment]
I think this explanation from @cmfcmf regarding workflow should be included in those docs: 

> We don't use the Git Flow technique. We have a single branch, dev, which receives pull requests from branches of forks. Whenever we feel like the dev is stable enough, we ask Jerry to update the main website with the code from the current dev.

**Comment by j-frost** [comment]
Another valuable piece of information: 
> Dummy users can be created using the TestUserData fixture (this should probably also be added to the README): 
>```bash
>php bin/console doctrine:fixtures:load --fixtures src/AppBundle/DataFixtures/ORM/TestUserData.php
>```

**Comment by cmfcmf** [comment]
> > We don't use the Git Flow technique. We have a single branch, dev, which receives pull requests from branches of forks. Whenever we feel like the dev is stable enough, we ask Jerry to update the main website with the code from the current dev.

Turns out we _do_ have a master branch, which is what's currently deployed to adventurelookup.com. I must've forgotten when I wrote the sentences above 😄 So, whenever we merge dev into master, we ask Jerry to deploy the new master branch.
