### ISSUE TITLE
Problems Getting Started

### ISSUE THREAD

**Issue by j-frost** [AdventureLookup/AdventureLookup#251]
So I was setting up the project on my machine using the recommended way via vagrant and ran into some problems. Well, really they're just minor annoyances I guess. 

* The vm starts with `pwd`=`/home/vagrant`. It took me asking on discord to realize I had to `cd` into `/vagrant`. @cmfcmf reckons this is probably because the `Vagrantfile`'s provisioning didn't finish properly. 

* The composer console complains about xdebug: `You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug`

* For some reason, the first time I started webpack in guest mode, I got a response of 500 when `GET`ting on /adventures. Worked after restarting webpack though, so maybe this is just a weird hiccup. I haven't tried to reproduce it yet. 

I'm running this on an Ubuntu 17.10, for a `uname -a` of `Linux 160163L 4.13.0-36-generic #40-Ubuntu SMP Fri Feb 16 20:07:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`.

**Comment by burnhamrobertp** [comment]
@cmfcmf does your recent work address any of the listed items above?

**Comment by cmfcmf** [comment]
Yes, the first point has been addressed by #254. The other points have not yet been addressed.

**Comment by cmfcmf** [comment]
This should all be fixed by #272.
