### ISSUE TITLE
Fix functional build errors

### ISSUE THREAD

**Issue by burnhamrobertp** [AdventureLookup/AdventureLookup#253]
Travis builds seem to be failing consistently for function tests thanks to some deprecation errors coming out of Symfony.

> Remaining deprecation notices (3)
>   1x: Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "knp_paginator" service to "Knp\Component\Pager\Paginator" instead.
>     1x in AdventureControllerTest::testDelete from Tests\AppBundle\Controller
>   1x: Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "knp_paginator" service to "Knp\Component\Pager\PaginatorInterface" instead.
>     1x in AdventureControllerTest::testDelete from Tests\AppBundle\Controller
>   1x: The JavierEguiluz\Bundle\EasyAdminBundle\Event\EasyAdminEvents class is deprecated since version 1.16 and will be removed in 2.0. Use the EasyCorp\Bundle\EasyAdminBundle\Event\EasyAdminEvents class instead.
>     1x in AdventureControllerTest::testDelete from Tests\AppBundle\Controlle

**Comment by cmfcmf** [comment]
I'll work on fixing these.
