### ISSUE TITLE
Clearing the level inputs doesn't reset the search

### ISSUE THREAD

**Issue by j-frost** [AdventureLookup/AdventureLookup#257]
This is in the new design. Clearing out the inputs for min starting level and max starting level doesn't remove the filters. This means that if I expand starting level range that only some options may be present although the user perceives to have reset the search filters. Only when looking in the center will they notice that there's still filters present. 

Not a biggie and I don't know if we really need to fix it, but a little unintuitive.

**Comment by cmfcmf** [comment]
This is fixed in #296. A new apply button appears after changing the level input fields.

**Comment by cmfcmf** [comment]
This is now live :tada:
