### ISSUE TITLE
Clicking the name of a filter won't activate it

### ISSUE THREAD

**Issue by j-frost** [AdventureLookup/AdventureLookup#258]
Clicking on the text of for instance 'Stone Giants' und "Common Monsters" doesn't toggle the filter. Only clicking next to the filter does. Probably need to move the click handler?

**Comment by dap6000** [comment]
aha, now i see. good catch. 

if the click is on the text, then the value of `event.target` is the inner `div` (or perhaps the `span` around the number). but the event handler moves around the DOM expecting the event target to be `div.option`. *and* the call to `$optionsList.on('click', '.option', …);` uses the optional param to specify a selector to filter events using the selector. when a click comes through with a target that doesn't match the `.option`  selector it gets ignored. 

relevant section in the JS is here:
https://github.com/AdventureLookup/AdventureLookup/blob/5e53fde15d0e2d14c2f1461c7c18bfa6caeb70ba/app/Resources/webpack/js/adventures.js#L19

the first two lines should be something like:
```
  $optionsList.on('click', e => {
   let $option = $(e.target).closest('.option'),
…
```
this will 1. allow events with targets inside `div.option` but not directly *on* `div.option` to fire the event handler and 2. make sure that `$option` refers to the proper `div.option` for the click for both click events with a target of `div.option` as well as click events with a target of a descendant of `div.option`. 

i should try to get a fork running locally. but not tonight.

**Comment by cmfcmf** [comment]
This is indeed some unwanted behaviour we should fix before the new design goes live. Thank you @j-frost for reporting and @dap6000 for your analysis!

**Comment by j-frost** [comment]
Any time.
