### ISSUE TITLE
API or anyway to access data directly?

### ISSUE THREAD

**Issue by pj4533** [AdventureLookup/AdventureLookup#260]
I'd love to write a native iOS front-end for AdventureLookup, but digging in a bit it looks like the data is put in the HTML directly without making any sort of (publicly available) API request?

Even if it were somewhat of a hack (and not a fully REST, JSON API), I'd be ok figuring it all out, if someone can point me in a direction!

Thanks in advance.

-pj

**Comment by cmfcmf** [comment]
Hi @pj4533,
as you noticed, there is no API available at the moment.
However, I'm unsure whether a public API is something @MattColville and @JohnnyFlash would agree with. Such an API would allow other people to create "Adventure Lookup" apps/websites/services, which would look like they were offically supported by Matt, when in fact, they might not be.
Don't get me wrong here, I'm not saying this is never going to happen (it's not my decision to make), but I'm concerned of the possible consequences of introducing a public API.

**Comment by pj4533** [comment]
I hear that...makes sense.   API doesn't have to be publicly usable by anyone though, it could be locked down so only approved clients can use it.   

Could be super simple to start and just embed a key in the app, check the key on the API side.   Not super secure or anything, but would probably be enough to discourage any unauthorized clients.  And if that did happen in the future, a more robust proper API public/private key mechanism could be implemented.

Just a thought!

**Comment by potecuta** [comment]
I came to the github page for exactly the same reason, creating an iOS app 'cause I'm bored and if it will help someone, so much better. Kinda disappointed that I can't :(

**Comment by pj4533** [comment]
@potecuta    any other ideas?   i'd love to work on a d&d-ish iOS side project!

**Comment by potecuta** [comment]
I have a couple of ideas, one of them being something similar to the roll20 map but having the option to view the app and characters in AR. Either way I think we should move the discussion to another place :)

**Comment by ArielLeslie** [comment]
I know that this is an old Issue, but I also came here largely to look into an API. The lack-of-control argument seems strange considering the MIT license on this project.

**Comment by cmfcmf** [comment]
FYI: I have created a PR to add REST API support in #297 that allows searching and listing adventures.
