### ISSUE TITLE
Incomplete Level Range not Displaying

### ISSUE THREAD

**Issue by BertBash** [AdventureLookup/AdventureLookup#266]
It appears that adventures which lack entries in both maximum and minimum level, but have an entry in one will not display that level range on the search results page.

This adventure has a minimum level of 7:
![advpage](https://user-images.githubusercontent.com/34818466/38532993-308f6a10-3c45-11e8-8f0c-60e0dea20cff.png)

But on the search results screen there is nothing to indicate that:
![nonshow](https://user-images.githubusercontent.com/34818466/38532714-11a3a798-3c44-11e8-841a-e2b53db2fd95.png)

Since we've got this information it seems like a waste not to display it. Perhaps incomplete level designations like this should be displayed as "7-?" or just as "7"?

**Comment by cmfcmf** [comment]
Thank you for reporting this @BertBash! 
I think you're right, we shouldn't hold off (incomplete) information we were given. I think both showing "7-?" or "7" would be fine.
