### ISSUE TITLE
I'd like an admin page that shows what curators have been doing

### ISSUE THREAD

**Issue by MattColville** [AdventureLookup/AdventureLookup#28]
You know, shit goes in there and I want to check it out and maybe edit it, but I can't see who's doing what.

This would also help us learn who the good curators are.

**Comment by jsaugustyn** [comment]
You mean, something like [this](https://new.adventurelookup.com/admin/?action=list&entity=Adventure)? We've added a basic admin functionality. It will be GREATLY improved once we simplify the current database structure. There will also be a login so only admins can monkey around in there.

**Comment by etchalon** [comment]
I can design one. How granular do you want the data, and what types of actions do you see yourself needing to take on that data?

**Comment by harkenn** [comment]
If the EasyAdmin system does work (even crudely) for the moment, its probably better to focus our efforts on the areas of the system that an automated system can't handle. We can always come back and replace the EasyAdmin auto-generated stuff with our own admin panel later.

**Comment by cmfcmf** [comment]
I've played around with this for a bit in my local environment. I've used the [Data-Dog AuditBundle](https://github.com/DATA-DOG/DataDogAuditBundle) and was able to produce the following overview:
![image](https://user-images.githubusercontent.com/2145092/28499831-38b1808c-6fbf-11e7-82fb-49af9f8e3af9.png)
When clicking on the magnifier icon, it looks like this:
![image](https://user-images.githubusercontent.com/2145092/28499836-4eddd400-6fbf-11e7-889f-f7d14ee3f779.png)

**Comment by MattColville** [comment]
Yeah this looks good! I can clearly see what edits folks have made.

Is that a little "undo" icon? That's nice. Seems like it could make versioning complex, but what do I know?

**Comment by harkenn** [comment]
Indeed, Matt, I would expect its probably quite a bit of complexity. If this actually implements not only an audit log but handles rolling back arbitrary changes, I'll be pretty impressed especially since it seems to have flown under the radar, judging by github stars and whatnot.

**Comment by cmfcmf** [comment]
It doesn't include a revert button. That would indeed be awesome.

**Comment by harkenn** [comment]
What's that little "arrow back" icon to the right of each audit entry?

**Comment by cmfcmf** [comment]
Nothing specific, if you click the link, it simply filters all log entries by that username / monster / adventure, etc. I don't really like it myself, too much of a distraction. It's there because it was present in the example which came with the bundle, which I largely copied for a first demo.

**Comment by cmfcmf** [comment]
This is done in #70.
