### ISSUE TITLE
I cannot log in after password reset

### ISSUE THREAD

**Issue by jasonmgilbert** [AdventureLookup/AdventureLookup#281]
After resetting my password, when I try to log in, I get an "invalid credentials" error.

I apparently created an account in the past but did not remember the password.  I requested a password reset, got the email, and reset the password.  The site then took me to the login page where I entered the password and it says invalid credentials.  I copied the password to a notepad file and pasted it in to the password reset fields and then in to the password field, so I know they were identical.

**Comment by cmfcmf** [comment]
Hi @jasonmgilbert, please make sure you are using your username, not your email address, when trying to login. Let me know if it works!

**Comment by jasonmgilbert** [comment]
Resolved
