### ISSUE TITLE
broken links to Frog God Games

### ISSUE THREAD

**Issue by miromonti** [AdventureLookup/AdventureLookup#282]
For [_The Blight: The Crucible_](https://www.adventurelookup.com/adventures/the-blight-the-crucible)
...the link there now (https://www.froggodgames.com/blight-crucible) should be updated to **https://froggodgames.com/frogs/product/tb4-the-crucible-2/**

For [_The Blight: Children of the Harvest_](https://www.adventurelookup.com/adventures/the-blight-children-of-the-harvest)
...the link there now (https://www.froggodgames.com/blight-children-harvest) should be updated to **https://froggodgames.com/frogs/product/tb5-children-of-the-harvest/**

I suspect other links to Frog God Games are also broken.

**Comment by JohnnyFlash** [comment]
These have been updated.
