### ISSUE TITLE
New Fields - Stars and votes

### ISSUE THREAD

**Issue by durnin** [AdventureLookup/AdventureLookup#285]
Just like any product page you can see around the web it would be nice to have an option as a user to vote on a particular adventure and give it a star qualification from 1-5. Logged in users should be the only ones able to vote and only 1 vote per user/adventure.
Then a filter by stars or most voted/stars could be added (like in Amazon) - so that I can for instance, look the most starred adventure for first levels on 3.5 d&d.

**Comment by fangxianfu** [comment]
I agree that this would be a great feature, as well as the ability to filter and sort by adventures' star ratings.

As a stretch goal it would be awesome if users could write text reviews, but I appreciate that that adds a lot of moderation overhead and that might not be desirable.

**Comment by Wigginns** [comment]
Checkout the dev branch at dev.adventurelookup.com. Thumbs up/down have been added as well as reviews.

**Comment by durnin** [comment]
That's a very nice addition @Wigginns . The difference I see with the approach I mentioned is the ability to be able to filter/sort by stars on the search page - which for me is the whole point.

**Comment by cmfcmf** [comment]
I'll close this issue in favour of #179 - reviews have been implemented (albeit without stars but simple thumbs up/thumbs down) and sorting adventures is tracked over at #179. The decision to not add stars is discussed in https://github.com/AdventureLookup/AdventureLookup/issues/16#issuecomment-315957462 if you are curious.
