### ISSUE TITLE
Request: Add setting of Midgard

### ISSUE THREAD

**Issue by subliminalchords** [AdventureLookup/AdventureLookup#286]
Midgard is the campaign setting for the majority of the work done by Kobold Press. Being able to filter this content would be very helpful as it's a popular campaign setting.

In adding it, updating the kobold press materials that are in the setting to have the tag would be helpful.

**Comment by Wigginns** [comment]
Going to close this. Though this setting has a decent amount of content, it seems that searching for Kobold Press publisher would mostly capture these. If there is more demand for it we can re-evaluate.
