### ISSUE TITLE
Open external links in new tab

### ISSUE THREAD

**Issue by HarmlessHarm** [AdventureLookup/AdventureLookup#287]
Hi there,

I think it would be nice to open links to external webpages in a new tab. That way you make sure people keep their AdventureLookup tab open.

**Comment by NorNamlin** [comment]
Any reason just right clicking the link and opening in a new tab doesn't work?

**Comment by cmfcmf** [comment]
I agree with @NorNamlin. Users who want to open links in a new tab can do that by right clicking / long tapping. If anyone else has strong feelings about this in the future, feel free to leave a comment.
