### ISSUE TITLE
Getting HTTP 500 errors going to detail pages

### ISSUE THREAD

**Issue by markd2** [AdventureLookup/AdventureLookup#291]
Hi!

When I follow a link on the page, I get a 500 error.

For instance, if I click _A Dungeon and a Dragon_ which goes to https://www.adventurelookup.com/adventures/a-dungeon-and-a-dragon, I get the 500.

I'm on OSX Catalina, 10.15.2 (19C57), Safari Version 13.0.4 (15608.4.9.1.3). Also happens in Chrome 79.0.3945.130 (Official Build) (64-bit)

| before | after| 
| ---- | ----- |
| <img width="1401" alt="Screen Shot 2020-02-07 at 3 02 02 PM" src="https://user-images.githubusercontent.com/609957/74061817-df75b780-49ba-11ea-8f65-e6dce654046c.png"> |  <img width="1401" alt="Screen Shot 2020-02-07 at 3 02 00 PM" src="https://user-images.githubusercontent.com/609957/74061839-eac8e300-49ba-11ea-82ea-291b689432b3.png"> |

**Comment by cmfcmf** [comment]
Thank you for reporting this!
@JohnnyFlash is looking into it.

**Comment by cmfcmf** [comment]
And has fixed it about an hour ago - should be all fine again!

**Comment by markd2** [comment]
you rule.  Thank you!!
