### ISSUE TITLE
Can't merge upstream

### ISSUE THREAD

**Issue by jsaugustyn** [AdventureLookup/AdventureLookup#30]
Hey, I'm having a problem merging the current master into my local respository to stay synced. Specifically, I am getting the following error:

`CONFLICT (modify/delete): ubuntu-xenial-16.04-cloudimg-console.log deleted in upstream/master and modified in HEAD. Version HEAD of ubuntu-xenial-16.04-cloudimg-console.log left in tree.
Automatic merge failed; fix conflicts and then commit the result.` 

I suspect this has to do with moving vagrant to gitignore, but I'm not sure how to fix it. Can anyone with more git experience help me out?

**Comment by harkenn** [comment]
You need to reset your logfile so that it hasn't been modified, but you can't do that while the VM is writing to it.

```
# Stop the VM
vagrant halt
 
# Reset your changes to that one file
git checkout ubuntu-*.log
 
# Merge in upstream (or whatever you called your remote)
git merge upstream
 
# Restart the VM
vagrant up
```

**Comment by harkenn** [comment]
If `git checkout ubuntu-*.log` doesn't work you could try removing the logfile entirely `rm ubuntu-*.log` and then try to merge in upstream.

**Comment by jsaugustyn** [comment]
`git checkout ubuntu-*.log` didn't work, so I tried removing the offending file. But, when I tried to merge upstream I now get the following error:

`error: merge is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.`

`git status` reveals:
`On branch master
Your branch is ahead of 'origin/master' by 13 commits.
  (use "git push" to publish your local commits)
You have unmerged paths.
  (fix conflicts and run "git commit")`

However, when I try `git commit -m MESSAGE` I get another error:
`U       ubuntu-xenial-16.04-cloudimg-console.log
error: commit is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.`

So...that appears to put me right back where I started. Grrr...

**Comment by harkenn** [comment]
Was there more output from `git status`? If there are unmerged paths it should list them.

**Comment by harkenn** [comment]
Also, you're in the middle of a merge so don't try to do anything else unless you abort the merge first.

**Comment by jsaugustyn** [comment]
Never mind, I'm an idiot. I actually removed the log file, but didn't remove it from git locally. Thanks for your help - I think I'm back in sync.
