### ISSUE TITLE
Add global anouncements bar

### ISSUE THREAD

**Issue by cmfcmf** [AdventureLookup/AdventureLookup#310]
I would like to have an announcement bar at the very top of each page that can be enabled by setting a parameter in the `app/config/parameters.yml` file. This bar could then be used to announce server maintenance or similar news. In addition, I would permanently enable it on dev.adventurelookup.com to say something along the lines of "Watch out! This is the development site. All data you insert here may be lost" or something similar.

**Comment by wetterlicht** [comment]
<img width="960" alt="annoncement-bar" src="https://user-images.githubusercontent.com/9221797/82140025-e0757b00-982c-11ea-9b35-50d1e431e345.png">

I took a quick shot at this. Is this kind of what you had in mind? And is the parameter in `app/config/parameters.yml` supposed to be the text of the announcement?

**Comment by cmfcmf** [comment]
Looks great!
> And is the parameter in app/config/parameters.yml supposed to be the text of the announcement?

:+1:

**Comment by cmfcmf** [comment]
Cross-referencing PR #319
