### ISSUE TITLE
Add spoiler text to reviews

### ISSUE THREAD

**Issue by Wigginns** [AdventureLookup/AdventureLookup#316]
Add the option to mark spoilers in a review.

**Comment by cmfcmf** [comment]
I have been thinking about this for a bit: Isn't looking at the adventure details (boss monsters, notable magic items, description) already a spoiler? I think what I'm asking is this: When should people use spoiler tags? I.e. what kind of review content is there that is more spoiler'y than what's already listed on the page?

Basically, what would the UI say about when to use spoiler tags in rewviews: "Use spoiler tags when... ???"

**Comment by Wigginns** [comment]
That’s a fair point. In theory this website should largely be used by dms looking to run the adventure. This feature is probably not useful for this site as it stands
