### ISSUE TITLE
Make the long list of filter options (e.g., notable items) filterable

### ISSUE THREAD

**Issue by cmfcmf** [AdventureLookup/AdventureLookup#318]
Each filter for string fields should have a search bar to more easily narrow down the options:
![image](https://user-images.githubusercontent.com/2145092/82141072-b07da600-9833-11ea-859b-a314ee9cfef3.png)

Typing into that search bar should filter the options available for that filter. That makes it easier to find the actual filter option(s) someone wants to use.

To be clear, these per-filter search bars are only an aid for finding the right per-filter options to then click the checkboxes to enable them. The value typed into these search bars should *not* be sent to the server.

**Comment by sinh343** [comment]
Had a go at this real quick, seems simple enough.

https://github.com/AdventureLookup/AdventureLookup/pull/325
