### ISSUE TITLE
Improve layout of the adventure details page

### ISSUE THREAD

**Issue by cmfcmf** [AdventureLookup/AdventureLookup#322]
IMHO the change requests should become their own separate box like the reviews box. Here's a quick mockup of what I mean (ignore the weird spacing, this is just to visualize the three white boxes and their order):

![image](https://user-images.githubusercontent.com/2145092/82141569-1cadd900-9837-11ea-942e-3458b1ee2177.png)

The title of the change requests box should have the same formatting as the title of the reviews box, of course.
As a bonus, it would be great if the white margin to the left and right of the blue and green boxes could also be removed.

What do you think about this idea?

**Comment by Wigginns** [comment]
Visual clarity is definitely a plus. An additional "nice to have" might be a collapsible change requests box. That way, when curators are browsing adventures they can more easily navigate to the reviews as change request lists are sometimes quite long.

**Comment by cmfcmf** [comment]
> An additional "nice to have" might be a collapsible change requests box. That way, when curators are browsing adventures they can more easily navigate to the reviews as change request lists are sometimes quite long.

Maybe we could collapse only resolved change requests and still display unresolved change requests? IMHO unresolved change requests should be visible immediately.
