### ISSUE TITLE
Minor stylistic improvements to adventure details page

### ISSUE THREAD

**Issue by cmfcmf** [AdventureLookup/AdventureLookup#323]
1. Bookmark dropdown should be right aligned, not left aligned like it currently is (there is probably a Bootstrap class for that):
![image](https://user-images.githubusercontent.com/2145092/82142048-e160d980-9839-11ea-8cbb-c3ee8e112e9d.png)
2. The details themselves are really crammed on mobile
![image](https://user-images.githubusercontent.com/2145092/82142075-09e8d380-983a-11ea-81cf-01345a9f337a.png)

  - first row should be: written by, published by, publication year
  - second row: setting, environments
  - third row: link
  - fourth row: handouts, battle maps, includes characters
  - fifth row: level (copied from the top of the page), soloable
  - sixth row: found in, part of
  - and then boss/common monsters and items in separate rows like they already are

**Comment by wetterlicht** [comment]
I'll take this one if I may. Are the changes to the rows/columns only for mobile or in general?

**Comment by cmfcmf** [comment]
👍 The changes to the rows were only based on my quick ideas when I looked at it on an (emulated) iPhone. But don't take them as definitive - feel free to do whatever looks and feels best. 
One thing I didn't look into is how the current design looks on tablets. If you work on this, it would be a great if you could also make sure it looks nice on those 💯
