### ISSUE TITLE
Make it easier to see whether a review is positive or negative

### ISSUE THREAD

**Issue by cmfcmf** [AdventureLookup/AdventureLookup#328]
I feel like it's a bit difficult to see at first glance whether a review is positive or negative:
![image](https://user-images.githubusercontent.com/2145092/82231614-afc93a80-992d-11ea-985c-c0fe0a0ba9e6.png)
Maybe we could replace the big quotation mark symbol by either a thumbs up or thumbs down icon, depending on the review?

**Comment by Wigginns** [comment]
I really like this. It'd be a quick at a glance way to know "good or bad".

**Comment by wetterlicht** [comment]
I'm on this. Thoughts on color vs no color?
<img width="684" alt="reviews" src="https://user-images.githubusercontent.com/9221797/82470101-306e6f00-9ac5-11ea-8599-fb2d6653e58a.png">

**Comment by cmfcmf** [comment]
Hmm, not sure. Maybe the colored versions are a bit too much? Could you also try out how it looks like when you use the outlined icon versions (e.g., https://fontawesome.com/v4.7.0/icon/thumbs-o-up) and color them?

**Comment by wetterlicht** [comment]
Outlined does look better I think. 
<img width="684" alt="reviews" src="https://user-images.githubusercontent.com/9221797/82504876-b5c14600-9afc-11ea-80d5-fa0a86a3789d.png">

**Comment by cmfcmf** [comment]
I prefer either the outlined colored versions or the filled greay versions of your first screenshot. Can't really decide though. Would be great to get some more opinions of the others :eyes:

**Comment by Wigginns** [comment]
Outlined color looks nice imo but I’m not against the filled grey. Both options add nice visual clarity of the review, good job.

**Comment by cmfcmf** [comment]
Given that we don't have a clear favourite, IMHO we should let @wetterlicht decide what they like best. Looking forward to a PR :+1:
