### ISSUE TITLE
Made a change to a record, now the record doesn't appear in search.

### ISSUE THREAD

**Issue by MattColville** [AdventureLookup/AdventureLookup#33]
I edited the Deep Horizon record because it was linking to a copyright-violating site, and now the record doesn't show up when I search for it.

To be clear, it did show up originally, that's how I found it.

This is not the first time this has happened to me. Last time Jerry rebuilt the index and that fixed it. This definitely needs to be fixed before I go on YouTube and promote this thing. :D

**Comment by jsaugustyn** [comment]
Did you edit it from the front end or the admin page?

**Comment by MattColville** [comment]
The front end.

**Comment by MattColville** [comment]
Is anyone looking at this bug? Seems like a big problem, that adventures aren't showing up.

Should I try and rope some more people into helping with this?

**Comment by harkenn** [comment]
This has to do with an unhandled case where editing an adventure does not trigger the elastic search reindex. I'll see about being able to pick this up sometime today. @cmfcmf would be preferred, so if he gets to it before I do, all the better.
