### ISSUE TITLE
Users should not be able to link to known bad sites

### ISSUE THREAD

**Issue by MattColville** [AdventureLookup/AdventureLookup#34]
People are going to want to post links in the URL field to illegal PDFs. By and large these PDFs are all hosted in a handful of sites, which we should be able to blacklist.

And we should be able to add to that blacklist.

Users who submit links to these sites should get an error "Please do not link to torrent sites or illegal pdfs."

It would also be nice if the admins would get an alert when this happens so if there are repeat offenders among the curators, we can ban them.

Which means we may need the facility to ban people. :D

**Comment by harkenn** [comment]
Can you provide a list of the would-be blacklisted sites, so that they are here for when someone gets to implementing this?

**Comment by etchalon** [comment]
I feel like "blacklists" are a game of wack-a-mole. Maybe we should whitelist instead?

How many valid sites are there where people can find downloadable adventure PDFs?

**Comment by MattColville** [comment]
Yeah whitelist is better.

DMs Guild/RPGNow, etc...
Paizo
Probably a bunch more. Like Goodman Games, etc...

**Comment by jsaugustyn** [comment]
Working on it!

**Comment by MattColville** [comment]
If you'd like me to provide a list of valid sites to whitelist, lemme know. Wouldn't take long.

**Comment by cmfcmf** [comment]
> If you'd like me to provide a list of valid sites to whitelist, lemme know. Wouldn't take long.

I think such a list would be appreciated! For reference, these are the domains currently used by the currently added adventures:

<table>
<tr><th>domain</th><th>count</th></tr>
<tr><td>http://dmsguild.com</td><td>36</td></tr>
<tr><td>http://paizo.com</td><td>22</td></tr>
<tr><td>http://drivethrurpg.com</td><td>13</td></tr>
<tr><td>http://amazon.com</td><td>10</td></tr>
<tr><td>http://wizards.com</td><td>9</td></tr>
<tr><td>http://rpgnow.com</td><td>2</td></tr>
<tr><td>http://reddit.com</td><td>1</td></tr>
<tr><td>http://members.iinet.net.au</td><td>1</td></tr>
<tr><td>http://froggodgames.com</td><td>1</td></tr></table>

**Comment by MattColville** [comment]
So, after doing some editing today, I am reconsidering whitelisting. Some folks write their own adventures and host them on their own sites. Some of these adventures are popular and well-done.

Maybe we just let people report torrent links and illegally hosted PDFs and I can cull those manually?

**Comment by etchalon** [comment]
How many of those are you seeing?

It'd be easy enough to just have an approval process in place for links from unknown domains. Just a question of how much work it'd add for the moderators, I guess.

**Comment by marlinpierce** [comment]
@MattColville  I propose the following design.

We maintain a list of forbidden sites (domains).  Other sites can be reviewed and marked as approved.  Marking them as approved removes them from the list of unreviewed sites, which need approval.

We allow links to unreviewed sites to be used, so technically we are blacklisting.  But the sites would only be used until they were reviewed and forbidden.

This works like youtube, where copyrighted material might be uploaded, but when it is found, it is taken down.

So, features are
-   Maintaining a list of forbidden sites.
-   Maintaining a list of reviewed/approved sites.
-   A page to manage and review all the sites used in links.

**Comment by cmfcmf** [comment]
This sounds good to me.

@jsaugustyn you are currently assigned to this issue. Have you made any progress on it yet?
