### ISSUE TITLE
Search criteria clears

### ISSUE THREAD

**Issue by NorNamlin** [AdventureLookup/AdventureLookup#343]
Here's the problem.

Lets say you want to search for all adventures of 1e.  You click the 1e box, hit apply filter and blango, you have the list of adventures made for 1e.

Now lets say you choose an adventure, look at it, then hit your back button to look at another adventure entry.  Hmm... doesn't work, you get an error.  That page was just there a second ago...

Not sure if this is strictly an Edge issue or if it also happens with other browsers.  Fortunately you can refresh the page and get the list again.  Oddly enough however, if you have to start over and re-apply the filter, the adventure list is not the same each time either.  It's totally random.  This makes scrolling through the adventures difficult and very infuriating.

Nor'Namlin

**Comment by Wigginns** [comment]
After successful testing on Chrome and Firefox, this seems to be an "edge case". Clicking back after navigating to an adventure results in an error "This page was just here a second ago". Refreshing results in a warning that form data will be resubmitted but the network tab reports no "errors". 

I am unable to reproduce your issue with sorting. The adventures are sorted in a random per session basis but it should persist though navigating around adventures and seems to work that way for me just fine on, even on edge.

**Comment by cmfcmf** [comment]
The weird refresh behavior happens because our search form uses a POST request instead of a GET request. Changing that is tracked in #249. It's on my TODO list to fix that for good, hopefully this week.
