### ISSUE TITLE
Created a new branch, dev, added branch protections

### ISSUE THREAD

**Issue by harkenn** [AdventureLookup/AdventureLookup#36]
Created the dev branch that will be used for active development. Changes to the dev branch will go out to the staging server (presumably automatically, once I can get something configured for it). The dev branch is protected and requires PRs to be approved by a contributor with write permissions before it gets merged in.

The paradigm moving forward will be that `master` is only merged into from `dev` and the branch protections require a code owner to review those changes and approve them.

So for all future PRs, be sure you're targeting `dev` as the destination. If these turn out to be a pain or overly restrictive we can change the settings at any time in the future. As a side note, there are still 2 teams, Backend and Frontend from the python attempt. I'll probably clean up those teams (and users) sometime tonight or tomorrow and remove them from the organization.

**Comment by jsaugustyn** [comment]
Awesome!

**Comment by harkenn** [comment]
Dev server is up at https://adventurelookup.harkenn.com

Setup using nginx instead of apache and php-fpm. Elastic search is running, though I'm not sure what I did to fix it. It was throwing some errors about not being able to find any nodes in the cluster, and as I was researching it, I came back and it was fixed.....I don't remember doing anything, so yeah...

I've added you two, @jsaugustyn and @etchalon as contributors to the project so that you can assist in reviewing pull requests. Please be thorough and don't take light of approving stuff.

**Comment by etchalon** [comment]
Thanks for the add! 

Assuming the dev server auto-deploys the dev branch?

**Comment by harkenn** [comment]
Not yet, I've not gotten anything quite that extensive configured yet.

**Comment by cmfcmf** [comment]
> Not yet, I've not gotten anything quite that extensive configured yet.

I assume we could use Travis to login to your server via SSH and pull changes on every dev build.

**Comment by jsaugustyn** [comment]
Thanks, @harkenn. Tagging @MattColville for his awareness.

Is there any way for us to mirror the production database? The sample content is fine, but using real data might make it easier to find issues and test solutions.

**Comment by harkenn** [comment]
I'd need to get a mysql dump from production to put in the server

**Comment by harkenn** [comment]
@johnnyflash you had said in a different issue, you're planning on putting in another vm for dev at dev.AdventureLookup.com?

**Comment by JohnnyFlash** [comment]
That is the case.  However, until Matt can make the add to the DNS it won't be possible.

**Comment by jsaugustyn** [comment]
Should we bother or just use the server @harkenn put up?

**Comment by MattColville** [comment]
I have created the DNS.

**Comment by harkenn** [comment]
Looks like it's test.AdventureLookup.com and points at the same ip as the production server.

**Comment by JohnnyFlash** [comment]
So the DNS entry is live ... but I haven't created the new server.

It seems to me that it made more sense for me to wait for the big database change PR to be submitted so I didn't have to convert the DB on two different servers.

**Comment by harkenn** [comment]
Sure, makes sense. I think those changes are in the `dev` branch, so you may be good to go?

**Comment by JohnnyFlash** [comment]
Yesterday when I went to bed, there was a big PR with a bunch of changes including the utf8 change.

If it's safe for me to make the database change with the code at the head of master, then I will do it.

**Comment by JohnnyFlash** [comment]
I just read in another issue that we don't have to change the database yet.

OK... a copying I will go :)

**Comment by JohnnyFlash** [comment]
The Dev server is up.  Chat with me in Discord to get the details.
