### ISSUE TITLE
Using search drop down under System/Edition filter

### ISSUE THREAD

**Issue by NorNamlin** [AdventureLookup/AdventureLookup#375]
So, when I use this drop down, I get the option of "unknown" as a choice.

However, when I select this, all of the listed modules it pulls have a System/Edition tied to them.

Someone please take a look into this when time permits.

Edit: I just checked other options, and they also populate similar.  May be a bug of sorts.

Using Edge incase that makes the difference.

Thanks.

**Comment by cmfcmf** [comment]
Could you check whether this is fixed at the dev site: https://dev.adventurelookup.com ?
I'm pretty sure I fixed this behavior in #366.

**Comment by NorNamlin** [comment]
It does work properly via your link.  It's just the live site that is having the issue it seems.

**Comment by cmfcmf** [comment]
Thank you for confirming that it works on dev! The fix is now also live on the production site :+1:
