### ISSUE TITLE
Low contrast in sidebar filter view

### ISSUE THREAD

**Issue by Sertion** [AdventureLookup/AdventureLookup#378]
The current sidebar filter view headings (`.filter .title`) have a [low contrast (4.39)](https://webaim.org/resources/contrastchecker/?fcolor=D5D6DA&bcolor=595F6F) for text that small (14 px). The [MDN page about color contrast](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Perceivable/Color_contrast) has a good explanation about this type of issues.

**Comment by cmfcmf** [comment]
Thank you for bringing this up. I have fixed this and many other contrast issues in #379 and opened another issue on generally improving accessibility: #380.

**Comment by Sertion** [comment]
Thank you for the quick response! Looking forward to the improvements!

**Comment by cmfcmf** [comment]
These changes are now live :tada:
