### ISSUE TITLE
Change readme's production server instructions

### ISSUE THREAD

**Issue by harkenn** [AdventureLookup/AdventureLookup#38]
Current version of the production server advocates for non-production configuration, notably, using `libapache2-mod-php7.0` instead of the significantly more performant `libapache2-mod-fastcgi`

When this is undertaken, it may be advisable to simply move to nginx for the ease of configuration and performance gains.

**Comment by etchalon** [comment]
Nginx is vastly preferred. What would need to happen on production so that everything was aligned @JohnnyFlash?

**Comment by JohnnyFlash** [comment]
The current production server is running under nginx. :)

**Comment by harkenn** [comment]
Muwahahahaha. Does it use php-fpm, then?

**Comment by JohnnyFlash** [comment]
fastcgi_pass unix:/var/run/php7.0-fpm.sock;
fastcgi_split_path_info ^(.+\.php)(/.*)$;
include fastcgi_params;

**Comment by harkenn** [comment]
Should we just remove the production server instructions then?

**Comment by JohnnyFlash** [comment]
While I know this is mainly for us, I don't want to make it difficult for someone else to setup a server if they want.

**Comment by harkenn** [comment]
Honestly the vagrant file ended up being more helpful than the readme's production instructions when I setup my production (dev) server.

**Comment by harkenn** [comment]
We'll keep the server instructions, they still need to be updated though
