### ISSUE TITLE
Doctrine charset should be utf8mb4

### ISSUE THREAD

**Issue by burnhamrobertp** [AdventureLookup/AdventureLookup#39]
Presently it is only utf8, which mysql built to only support up to 3 bytes of character data, which excludes a whole lot of character that are in the "UTF-8" charset. It is unilaterally recommended to change from utf8 to utf8mb4.

This is easy to do for local development environments and the staging server; we wipe the data and rebuild the database with no fuss. Production will have to be manually migrated. Fortunately its not difficult.

https://mathiasbynens.be/notes/mysql-utf8mb4

**Comment by cmfcmf** [comment]
Oh boy. Naming something utf8 which isn't utf8... 💯

**Comment by JohnnyFlash** [comment]
Which order should the changes be made?  Should I modify the DB before the code or does it have to happen together?

**Comment by harkenn** [comment]
Code changes definitely have to go out or to app might have issues

**Comment by harkenn** [comment]
Code changes applied to dev per PR #40. Did some testing and the code changes (which change the php -> db connection string to use "utf8mb4") do not have any negative effect. So even though the schema / tables may be "utf8" and the application is connecting using "utf8mb4" the application seems to continue to work normally.

**Comment by harkenn** [comment]
We'll keep this ticket open until those changes are applied to production and the schema/table charsets can be changed to utf8mb4.

**Comment by cmfcmf** [comment]
Have you made progress on this @harkenn?

**Comment by harkenn** [comment]
Yes I already have the script that needs to be run. I probably aught to just write it into a command that we can later delete.
