### ISSUE TITLE
Change to Profile layout.

### ISSUE THREAD

**Issue by NorNamlin** [AdventureLookup/AdventureLookup#399]
Would it be possible to have the need to be completed change requests listed before adventure entered and reviews on the profile page?  This would draw attention to requested changes that need to be completed rather than have them at the bottom of the page where they tend to be ignored?

**Comment by Wigginns** [comment]
Your suggestion is just that change requests be the default tab here in the user profile?
![image](https://user-images.githubusercontent.com/3180645/93262318-403f4c80-f761-11ea-81a8-79fd8f7c1b0c.png)

**Comment by NorNamlin** [comment]
No, I'm asking that on the "Your Adventures" tab, the adventures with others pending change requests be listed at the top rather than at the bottom as they are currently.

The reasoning for this is that many people do not scroll down to even notice that there are requested changes that need to be made to their entry.

Alternately, a separate tab for "Requested Changes" or some such might also help, and it should be the default tab rather than "Your Adventures"

**Comment by Wigginns** [comment]
I played with this for a bit on the dev site today. It looks like when a change request is made it bubbles to the top of the "Your Adventures" tab already. I didn't want to play crap data on the live site. Is it behaving differently there?

**Comment by NorNamlin** [comment]
That's fine then.  I guess I didn't have any active change requests on my account to see that they already filter to the top.  Thank you for looking into this.
