### ISSUE TITLE
Monster & MonsterType entities

### ISSUE THREAD

**Issue by harkenn** [AdventureLookup/AdventureLookup#42]
Similar to the setting, implement a static data format for Monsters and store it in an entity, generate its migration(s) and repository, and create a fixture to populate a subset of data for development purposes. Also, add it to the adventure/show and adventure/edit views and ensure the data is searchable via the free-text search box at the top of the adventures/index page. Relationship would be ManyToMany between Adventure and Monster. 
**Entity properties:**
* Name (string)
* Type (foreign key)
* Unique (boolean)

**Example dataset:**
Orc, Humanoid
Kobold, Humanoid
Goblin, Humanoid
Gnoll, Humanoid
Hobgoblin, Humanoid
Beholder, Aberration
Black Pudding, Ooze
Mind Flayer, Aberration
Drow, Humanoid
Wyrmling, Dragon
Bulette, Monstrosity
Hill Giant, Giant
Stone Giant, Giant
Frost Giant, Giant
Storm Giant, Giant
Kuo-Toa, Humanoid
Lich, Undead
Slaad, Aberration
Umber Hulk, Monstrosity
Arcanamite, Monstrosity
Warhorse, Beast
Gazer, Aberration
Skin Bat, Undead
Deva, Celestial
Unicorn, Celestial
Pegasus, Celestial
Eye Golem, Construct
Homunculus, Construct
Flesh Golem, Construct
Myr, Construct
Stone Golem, Construct
Azer, Elemental
Djinni, Elemental
Gargoyl, Elemental
Salamander, Elemental
Spark, Elemental
Water Elemental, Elemental
Annis Hag, Fey
Boggle, Fey
Cactid, Plant
Dragonleaf Tree, Plant
Myconid, Plant
Vegepygmy, Plant
Baneling, Fiend
Night Hag, Fiend
Hell Hound, Fiend
Ink Devil, Fiend
Rakshasa, Fiend
Rakshasa, Fiend
Coral Drake, Dragon
Ash Drake, Dragon
Dragon Turtle, Dragon
Luck Dragon, Dragon
Pseudodragon, Dragon
Star Drake, Dragon
**Uniques**
River King, Fey
Sarastra, Fey
Kalarel, Humanoid
Balor, Fiend
Akyishigal, Fiend
Alquam, Fiend
Zmey, Dragon

**Monster Type example dataset**
**3e 3.5e**
Aberration
Animal
Beast
Construct
Deathless
Dragon
Elemental
Fey
Giant
Humanoid
Magical Beast
Monstrous humanoid
Ooze
Outsider
Planetouched
Plant
Shapechanger
Undead
Vermin
**4e**
Animate
**5e**
Celestial
Monstrosity
Fiend

**Comment by JohnnyFlash** [comment]
How would a homebrew add featured/named enemy?  Would that go under the Villain category?

**Comment by harkenn** [comment]
The structure of the "Monster" entity will be static, but the actual collection of data would still be able to be appended to. Users could add missing monsters or homebrew monsters.

**Comment by harkenn** [comment]
Should the relationship between Monster and MonsterType be ManyToOne (monsters.monster_type_id) or ManyToMany (pivot table)?

Some monsters have changed types (they were a "monstrous humanoid" in 3e and are just "monstrosity" in 5e)

**Comment by etchalon** [comment]
I'd go ManyToMany, for future flexibility.

**Comment by cmfcmf** [comment]
Done in #58.
