### ISSUE TITLE
Can we set up Projects?

### ISSUE THREAD

**Issue by jsaugustyn** [AdventureLookup/AdventureLookup#43]
It would be helpful to know what people are working on so we don't duplicate effort. Can we use the kanban feature of Projects for that? If so, can I get access to the Projects functionality?

**Comment by jsaugustyn** [comment]
For example, I'm working on the whitelist feature Matt wanted. Would be good to make sure nobody else is doing the same, or if they are, coordinating.

**Comment by etchalon** [comment]
I'm JUST working on the FE. Specifically trying to do nothing else so I don't get distracted.

**Comment by harkenn** [comment]
For issues that exist, can you assign yourself? That's typically the appropriate way to indicate you're working on something.

**Comment by jsaugustyn** [comment]
OK, that works!
