### ISSUE TITLE
Edition entity

### ISSUE THREAD

**Issue by harkenn** [AdventureLookup/AdventureLookup#46]
Implement a static data format for Editions and store it in an entity, generate its migration(s) and repository, and create a fixture to populate a subset of data for development purposes. Also, add it to the adventure/show and adventure/edit views and ensure the data is searchable via the free-text search box at the top of the adventures/index page.

Ensure the generated table is singular.

**Entity properties**:
* Name (string)
* Order (int)

**Example data**:
* OD&D, 10
* AD&D, 20
* 3e, 30
* Pathfinder, 40
* 3.5e, 50
* 4e, 60
* 5e, 70

I've never played in it, but from some research it sounds as if B/X and BECMI didn't really change enough compared to the OD&D basic rules to warrant separate categorization? In any case, this is just an example, the admin interface would need to support adding more editions.

**Comment by jsaugustyn** [comment]
Most people think of B/X as distinct from OD&D. The rules are relatively simple, but there are differences in things like ability score bonuses. OSR purists would also argue that B/X is distinct from BECMI. For example, the XP ranges for levels are different. But yeah, we should be able to add other categories via the admin portal.

**Comment by etchalon** [comment]
Would a parent-child relationship between Systems be helpful? I'm not familiar with enough of the systems to know whether a DM would want to include "sub-systems" or offshoots inside a search.

**Comment by harkenn** [comment]
@etchalon probably not, I think you'd be more likely to confuse people who wouldn't understand why a sub-system's adventures were coming back in the search result when they didn't expect them to.

**Comment by cmfcmf** [comment]
In addition to @harkenn's comment, I think we should keep it as simple as possible and finish the move to a static model as fast as possible. Otherwise we may be stuck forever in our current transitioning phase.

**Comment by jsaugustyn** [comment]
Agreed on all fronts. No need to set sub-systems, and let's keep it as simple as possible to get the next release pushed. Once we have the data model in place we can refine it as needed.
