### ISSUE TITLE
Environment entity

### ISSUE THREAD

**Issue by harkenn** [AdventureLookup/AdventureLookup#48]
Implement a static data format for Environment and store it in an entity, generate its migration(s) and repository, and create a fixture to populate a subset of data for development purposes. Also, add it to the adventure/show and adventure/edit views and ensure the data is searchable via the free-text search box at the top of the adventures/index page.

Ensure the generated table is singular.

**Entity properties:**
* Name

**Comment by cmfcmf** [comment]
As per [Matts comment](https://www.reddit.com/r/mattcolville/comments/6l9ogx/if_youre_working_on_a_version_of_adventure_lookup/djvdbp1/), the following environments should be predefined: 
> Dungeon, Wilderness, Swamp, City, Town, Ship, Underdark, Underwater, Stronghold, Planes
