### ISSUE TITLE
Implement correct permission scheme

### ISSUE THREAD

**Issue by cmfcmf** [AdventureLookup/AdventureLookup#57]
The current permission model lacks in a few important aspects, i.e. everyone can create an account and simply delete all adventures. This needs to be fixed until Matt makes a video and opens ADL to a larger audience. Here is my proposed, simple model (keep in mind, we want this to happen as fast as possible). All access levels can do everything listed above in addition to their level. Note that there is no approval process in this design.

### Guests
Can view and search adventures.

### Users (everyone can create such an account) `ROLE_USER`
Can create new adventures, can edit and delete adventures **they created**.
Can comment on all adventures to suggest changes (really just a text input they can dump suggested changes into. This could of course be improved by allowing them to directly say which field to change to which value, but for now a simple comment box should be sufficient).

### Curators (selected people only) `ROLE_CURATOR`
Can create and edit all adventures.
Can access the EasyAdmin backend **except for user table**.

### Admins (Matt, Jerod, ...) `ROLE_ADMIN`
Can view user list and recent activity
Can access the full EasyAdmin backend

**Comment by jsaugustyn** [comment]
I think this looks sensible. I would add that Curators and Admins can access the admin backend. Only Admins can CRUD Users through the admin backend.

Also, for the suggested changes, would those be sent to the original author in an email notification? Seems like we'd want some way to notify authors and/or curators that changes have been suggested.

**Comment by MattColville** [comment]
Looks good to me!

**Comment by cmfcmf** [comment]
This is done in #70.
