### ISSUE TITLE
Add code for Google Analytics 

### ISSUE THREAD

**Issue by JohnnyFlash** [AdventureLookup/AdventureLookup#63]
If we could add the basic code and fill it in from a variable in the config that would be great!

**Comment by harkenn** [comment]
Can you add an Analytics code so it's ready to go when a dev picks this up?

**Comment by JohnnyFlash** [comment]
I will do it tonight.
google_analytics_code:

**Comment by JohnnyFlash** [comment]
parameter added to both prod & dev sites

**Comment by cmfcmf** [comment]
Now that I think of it, I had already added Google Analytics to my demo site. [The code is still there](https://github.com/AdventureLookup/AdventureLookup/blob/master/app/Resources/views/base.html.twig#L83-L93) and should be replaced by the new code.
