### ISSUE TITLE
Click on whole adventure card to open adventure detail

### ISSUE THREAD

**Issue by JohnnyFlash** [AdventureLookup/AdventureLookup#65]
Just a thought, what do people think?

**Comment by harkenn** [comment]
Whole card could probably be clickable, no? Like...the whole card? Why else would any user be clicking on it?

**Comment by MattColville** [comment]
Yeah people are used to clicking on thumbs.

I'm trying to imagine a scenario where a user would expect any other result than "if I click anywhere in here, it opens the adventure." Maybe they see a entity they want to click on, and search that way? I dunno. I think we'd be safe making the whole card clickable.

**Comment by xDaizu** [comment]
Not to reopen a closed discussion, but I have a suggestion according to clickable sections of the adventure card: 

- Clicking on the image thumbnail opens the adventure, just like clicking on the name
- Clicking on sections like Edition, Setting or Starting Level links to a search using that criteria.

> For instance,"I2 Tomb of the Lizard King": if you click on "Edition AD&D" I would expect it to give me a search for AD&D adventures.  If this would clear previously selected filters or not is up to debate 
> ("search for AD&D as only criteria" vs "add AD&D to the current criteria" ).

Could this be discussed here or maybe this requires opening another (linked) issue?

**Comment by burnhamrobertp** [comment]
That is one possible choice for how we could design it, but because filtering on the "main stuff" like editions, setting, and level are easy, I'm not sure there is a compelling reason to make it function this way. For the vast majority of users, the optimal UX is that clicking anywhere on the card would load that adventure

**Comment by cmfcmf** [comment]
This is fixed with the new ui, which is already merged into dev.
