### ISSUE TITLE
Database migration failing

### ISSUE THREAD

**Issue by jsaugustyn** [AdventureLookup/AdventureLookup#71]
I am trying to set the latest version up on a different computer. Install is fine until the database setup step, which fails with the following error:

`Migration 20180000000000 failed during Execution. Error Number of tag names changed!`
`[Doctrine\DBAL\Migrations\AbortMigrationException] Number of tag names changed! `

**Comment by jsaugustyn** [comment]
I'm synced with the dev branch, in case that matters.

**Comment by harkenn** [comment]
@jsaugustyn cmfcmf's migrations which are designed to only work on production are causing you errors. Check doctrine docs on how to only run migrations up to a certain version. I'm pretty sure cmfcmf's "bad" one is the very last one.

**Comment by jsaugustyn** [comment]
OK, cool, thanks @harkenn. I've had to step away for a few days due to work demands. How close are we on refactoring the models?

**Comment by jsaugustyn** [comment]
I've tried rolling back to previous migrations, and am now getting errors on reindexing elastisearch:

`Base table or view not found: 1146 Table 'adl.edition' doesn't exist `

This is obviously related to the model refactoring. Suggestions are welcome, but I'll also dig around the elastisearch docs. It would be worth updating the README to note that the installation instructions won't currently work, and will be updated post-refactor.

**Comment by jsaugustyn** [comment]
Incidentally, if I roll back to the previous migration (20170721075547) I get the following errors on reindexing elastisearch:

`[Doctrine\DBAL\Driver\PDOException]                                                  
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.part_of' in 'field list' '

and

`[PDOException]                                                                       
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.part_of' in 'field list' `

These are both SQL errors.

**Comment by jsaugustyn** [comment]
Progress! If I run the very last migration (20180000000000) the initial elastisearch reindex works. However, I am unable to populate the database with dummy data. The current instructions in the README are to run:

`php bin/console doctrine:fixtures:load --fixtures src/AppBundle/DataFixtures/ORM/TagData.php --fixtures src/AppBundle/DataFixtures/ORM/RandomAdventuresData.php -n`

TagData no longer appears to exist - I think it was used in old dynamic model. Also, it is no longer RandomAdventuresData, but RandomAdventureData.

Fixing all that, I now get:

`[Symfony\Component\Debug\Exception\ContextErrorException]  
  Notice: Array to string conversion   `

I'll keep trying to fix this. If I can figure it out I'll update the README in a new pull request.

**Comment by jsaugustyn** [comment]
OK, so I tried running my own fork that does not include any of the model refactoring and it works as expected. @cmfcmf and @harkenn, am I better off waiting to do any additional work until the refactoring is totally complete and merged into the dev branch? I could keep chasing errors, but it might be simpler to wait until we are back to a stable branch.

**Comment by cmfcmf** [comment]
Hey @jsaugustyn, sorry for all the confusion. Here are a few things:
- You read the master's README. The command to load fixtures has already been adjusted in the [dev's README](https://github.com/AdventureLookup/AdventureLookup/blob/dev/README.md).
- Make sure to run `php bin/console app:elasticsearch:reindex` after loading fixtures.
- Don't run the fixture `Version20180000...`. It is not designed to run locally, but only on the live sites. Execute `php bin/console doc:migr:migr Version20170724185627` and replace the version by the name of the last fixture before the `Version20180000...` fixture . Maybe I shouldn't have made it a fixture but rather a command, to avoid the confusion 😕

To conclude: 
1. Make sure your current fork is running and working.
2. Pull changes from `dev`
3. Execute `php bin/console doc:migr:migr Version20170724185627` 
4. Execute `php bin/console app:elasticsearch:reindex`

Let me know if it works. If it doesn't, another option is to drop all tables from the database and continue at step 2 above.

**Comment by harkenn** [comment]
Technically you didn't make it a fixture, you made it a migration, but either way, you've changed that now.

**Comment by cmfcmf** [comment]
> Technically you didn't make it a fixture, you made it a migration, but either way, you've changed that now.

Thanks, always mixing the two terms up. Updated my comment above.

**Comment by jsaugustyn** [comment]
This isn't working. Here is exactly what I have done:

1. I forked this repository to jsaugustyn/AdventureLookup
2. I cloned jsaugustyn/AdventureLookup locally
3. I ran through the old setup instructions - everything works and the app runs
4. I set this repository as the remote upstream and did a `git fetch upstream`
5. I switched to a new branch based on upstream/dev: `git checkout -b newmodels upstream/dev`
6. I relaunched vagrant with `vagrant up` and `vagrant ssh`
7. I ran `php bin/console doc:migr:migr` and got the following error:

`PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "google_analytics_code". in /vagrant/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:100
Stack trace:
#0 /vagrant/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php(56): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('google_analytic...')
#1 /vagrant/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(217): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get('google_analytic...')
#2 /vagrant/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(187): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveString('%google_analyti...', Array)
#3 /vagrant/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ in /vagrant/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php on line 100`

8. Attempting `php bin/console app:elasticsearch:reindex` generates the same fatal PHP error.

**Comment by cmfcmf** [comment]
Ahh! Sorry. Another PR introduced a new configuration variable. Run `composer install` and hit enter when asked for `google_analytics_code`.

**Comment by jsaugustyn** [comment]
OK, solved that problem. But now `php bin/console doc:migr:migr` throws:

`Migration 20180000000000 failed during Execution. Error Number of tag names changed!`
`[Doctrine\DBAL\Migrations\AbortMigrationException]  
  Number of tag names changed!`

It appears to be running the 20180000000000 migration. Do I need to add a version to `php bin/console doc:migr:migr`?

**Comment by cmfcmf** [comment]
I've just noticed that the `Version20180000000000` appeared again due to merging. Sorry about that. Could you [merge my PR](https://github.com/AdventureLookup/AdventureLookup/pull/74) which removes it once more, please? Then pull changes from dev for the last time and you should be up and running!

**Comment by jsaugustyn** [comment]
OK, I think it's working now. Just to confirm - I am no longer seeing any metadata (setting, edition, etc) for the random adventure data and there are no filters displaying. Is that as it should be?

**Comment by cmfcmf** [comment]
If you generate the random adventures again, their data should show up once more.

    php bin/console doctrine:fixtures:load --fixtures src/AppBundle/DataFixtures/ORM/RandomAdventureData.php

**Comment by jsaugustyn** [comment]
That gives the following error:

`[Symfony\Component\Debug\Exception\ContextErrorException]  
  Notice: Array to string conversion`

**Comment by cmfcmf** [comment]
After re-indexing, these should be gone too!

    php bin/console app:elasticsearch:reindex

**Comment by jsaugustyn** [comment]
Nope. I re-indexed, then tried running this again. Same error, and still no metadata.

**Comment by cmfcmf** [comment]
I just reproduced the bug locally. Try changing line 80 of the `RandomAdventureData` fixture to 
`->setFoundIn($faker->catchPhrase)`, then 

    php bin/console doctrine:fixtures:load --fixtures src/AppBundle/DataFixtures/ORM/RandomAdventureData.php
    php bin/console app:elasticsearch:reindex

**Comment by jsaugustyn** [comment]
That's how line 80 is already

**Comment by cmfcmf** [comment]
I'm so sorry - I meant line 81. Looks like I'm too tired to think.
> ->setPartOf($faker->boolean() ? $faker->catchPhrase : null)

**Comment by jsaugustyn** [comment]
SUCCESS!!!! Thanks - get some sleep!

**Comment by harkenn** [comment]
@jsaugustyn closable?

**Comment by jsaugustyn** [comment]
Yeah, I'll close #71
