### ISSUE TITLE
Bug: author_list:"" and artist_list:"" search terms do not work

### ISSUE THREAD

**Issue by dHelmgren** [AdventureLookup/AdventureLookup#77]
When clicking an author or artist's name on an entry, the browser redirects to a search of author_list:"Firstname Lastname", but the entries found when searching for that author without the author_list:"" tags do not appear.

**Comment by caberlitz** [comment]
The "monster_list:" is also not working, if I click in any monster name it does not return any result, not even the one from where I clicked.

**Comment by cmfcmf** [comment]
Hey @dHelmgren and @caberlitz. Thank you for taking the time to report bugs! 
However, can you confirm you are using http://new.adventurelookup.com? We don't use the words `monster_list` and `author_list` over there :/

**Comment by caberlitz** [comment]
@cmfcmf Thanks for the quick reply, I can confirm you that I wasn't using the one you provided the link for. Good that you replied before I uploaded more adventures in it.

**Comment by jsaugustyn** [comment]
@caberlitz which URL were you using?

@JohnnyFlash and @cmfcmf we should take down any other versions of the site to avoid this kind of confusion.

**Comment by caberlitz** [comment]
@jsaugustyn I've used this one: https://adventurelookup.herokuapp.com/
Can any of you give me the information if this one was an old version or totally unrelated?

**Comment by harkenn** [comment]
That is a prototype built by another developer.

**Comment by dHelmgren** [comment]
Ah, good to know. I think the Herokuapp.com link comes up earlier on searches, so that may be part of the problem. Thanks for the info, closing the issue.
