### ISSUE TITLE
Filter by Length (# of Pages) bug

### ISSUE THREAD

**Issue by bringerofdoom** [AdventureLookup/AdventureLookup#78]
Can't get this to work. No matter what range of pages I apply, no filter actually goes into effect. All adventures remain listed, regardless of their page count.

**Comment by cmfcmf** [comment]
Hey @bringerofdoom, thank you for reporting this bug!

This is a known issue and has already been fixed. We are working on a few last things and will push this bugfix and many other improvements out to the live site over the next few days.
Leaving this open until the bugfix is live.
