### ISSUE TITLE
Need An "D&D Only" alert when adding an adventure

### ISSUE THREAD

**Issue by MattColville** [AdventureLookup/AdventureLookup#8]
Someone busted their ass and added a ton of Star Wars data to the site, and I had to delete it because AL.com is D&D specific. 

I want to make sure that doesn't happen again, so when someone clicks "Add an adventure" we need some text somewhere saying "AdventureLookup is for D&D and it's clones. Not other systems/genres."

**Comment by cmfcmf** [comment]
I have created a pull request in #9 which adds this message to the page.
Once it is merged, it has to be deployed to your servers. I don't know if there is any automated process to do that (yet), @JohnnyFlash?
