### ISSUE TITLE
Damn! error

### ISSUE THREAD

**Issue by caberlitz** [AdventureLookup/AdventureLookup#80]
I apparently disapproved and/or deleted an adventure that I had previously added while editing it. Now, if I try and add it again, I receive a page with only "Damn!" written in it and the adventure is not added and does not appear in search.

**Comment by harkenn** [comment]
Just to confirm, this is at new.adventurelookup.com/adventures right? What is the name of the adventure?

**Comment by caberlitz** [comment]
Yes, it is in the new.adventures, I've learned from the previous mistake, sorry. The name of the adventure is Death in Freeport

**Comment by JohnnyFlash** [comment]
Reindexing brought it back... This is a known issue we are currently working on.
