### ISSUE TITLE
Unable to Suggest Changes

### ISSUE THREAD

**Issue by dHelmgren** [AdventureLookup/AdventureLookup#86]
A few times, I've seen issues with adventures that have already been posted that need to be changed. Unfortunately, there doesn't seem to be any way to flag an entity as incorrect or to suggest a change.

Example: in the entry for [A3 Assault on the Aerie of the Slave Lords](https://new.adventurelookup.com/adventures/assault-on-the-aerie-of-the-slave-lords) the Thumbnail references a similar looking image that is really the cover for "B3 Palace of the Silver Princess".

**Comment by cmfcmf** [comment]
You're in luck! This feature has just been implemented and merged yesterday (#81). It will be available with the next update.
