### ISSUE TITLE
Restrict Environment List

### ISSUE THREAD

**Issue by MattColville** [AdventureLookup/AdventureLookup#94]
I know there's a term for this, "validated list" is what Excel calls it, but the Environment list should work like the Setting or System where you can't just type in whatever you want.

The problem with the current "anything goes" setup is that people **searching** want "adventures on a ship." But people adding adventures want to get incredibly specific and say "Ocean" or "Sea" or "High Seas" or "Aquatic."

Which is a huge mess, especially since people searching want "On a ship" or "underwater" and those are two important differences people often look for, but which people entering adventures will use confusing terminology to describe and that makes unhappy users.

I can provide a validated list. Not sure what to do with the existing adventures. I'm currently just going through them all manually and making them conform to this list;

Extraplanar
Abyss/Nine Hells
City/Urban
Town/Village
Stronghold (Castle/Keep/Tower)
Ship
Underwater
Caves
Dungeon
Feywild
Desert
Forest
Wilderness
Swamp
Ruins
House/Mansion
Temple/Church
Island
Jungle
Mountain
Sewer
Underdark
Other

**Comment by MattColville** [comment]
Alright, I've edited...all the adventures to make sure they comply with the above list. Is it possible to now restrict future edits to just this list?

I'm planning on making The Video this weekend, but I can wait until after this change goes in. Once thousands of people are pounding on the site, we're going to see crazy (and counterproductive) entries to this field if we don't restrict it.

**Comment by cmfcmf** [comment]
> Alright, I've edited...all the adventures to make sure they comply with the above list. Is it possible to now restrict future edits to just this list?

Alright, cool! Users hadn't been able to add their own custom environments to adventures since 'the big merge'. All that's left to do then is to go to the admin interface and simply delete all environments you no longer want users to be able to choose: https://adventurelookup.com/admin/?entity=Environment&action=list&menuIndex=4&submenuIndex=-1

**Comment by MattColville** [comment]
I already did! Mission accomplished! :D

**Comment by cmfcmf** [comment]
Perfect, let's close this issue then 👍
