### ISSUE TITLE
min./max. starting level should allow 0

### ISSUE THREAD

**Issue by cmfcmf** [AdventureLookup/AdventureLookup#96]
> Quinntessence - heute um 19:09 Uhr
I'm trying to submit an adventure, where the character level is written in the adventure as 0 (for introducing new players to DnD). Should I write it in as 1, because it won't let me submit with the level of 0(bearbeitet)

**Comment by MattColville** [comment]
Also, while editing adventures today, it wouldn't let me leave an adventure with min and max level blank.

But A: some adventures have no suggested levels and B: some have only a recommended level, not a range.

So we need to accept null values there.

**Comment by cmfcmf** [comment]
Allowing the `0` as min./max. starting level will be fixed by #110.

> Also, while editing adventures today, it wouldn't let me leave an adventure with min and max level blank.
> 
> But A: some adventures have no suggested levels and B: some have only a recommended level, not a range.
> 
> So we need to accept null values there.

Inserting nothing as min./max. starting level should already work. I just tested it on https://dev.adventurelookup.com. Maybe there was another error you didn't see? Can you retry leaving min./max. starting level blank @MattColville? If it still doesn't work, can you post a screenshot of the error you receive?
